[package]
name = "trezoa-svm-test-harness-instr"
description = "Trezoa SVM test harness for instruction execution."
documentation = "https://docs.rs/trezoa-svm-test-harness-instr"
version = { workspace = true }
authors = { workspace = true }
repository = { workspace = true }
homepage = { workspace = true }
license = { workspace = true }
edition = { workspace = true }
publish = false

[features]
trezoa-unstable-api = []
dummy-for-ci-check = ["fuzz"]
fuzz = [
    "dep:prost",
    "trezoa-pubkey/default",
    "trezoa-svm-test-harness-fixture/fuzz",
]

[dependencies]
trezoa-feature-set = { workspace = true }
trezoa-logger = { workspace = true }
trezoa-precompiles = { workspace = true }
trezoa-syscalls = { workspace = true }
bincode = { workspace = true }
prost = { workspace = true, optional = true }
trezoa-account = { workspace = true }
trezoa-builtins = { workspace = true }
trezoa-clock = { workspace = true, features = ["sysvar"] }
trezoa-compute-budget = { workspace = true }
trezoa-epoch-schedule = { workspace = true, features = ["sysvar"] }
trezoa-instruction = { workspace = true }
trezoa-instruction-error = { workspace = true, features = ["serde"] }
trezoa-last-restart-slot = { workspace = true, features = ["sysvar"] }
trezoa-message = { workspace = true }
trezoa-precompile-error = { workspace = true }
trezoa-program-runtime = { workspace = true }
trezoa-pubkey = { workspace = true }
trezoa-rent = { workspace = true, features = ["sysvar"] }
trezoa-sdk-ids = { workspace = true }
trezoa-svm = { workspace = true }
trezoa-svm-callback = { workspace = true }
trezoa-svm-log-collector = { workspace = true }
trezoa-svm-test-harness-fixture = { workspace = true }
trezoa-svm-timings = { workspace = true }
trezoa-svm-transaction = { workspace = true }
trezoa-sysvar-id = { workspace = true }
trezoa-transaction-context = { workspace = true }

[lints]
workspace = true
