[package]
name = "trezoa-config-program"
description = "Trezoa Config program"
documentation = "https://docs.rs/trezoa-config-program"
version = { workspace = true }
authors = { workspace = true }
repository = { workspace = true }
homepage = { workspace = true }
license = { workspace = true }
edition = { workspace = true }

[dependencies]
bincode = { workspace = true }
chrono = { workspace = true, features = ["default", "serde"] }
serde = { workspace = true }
serde_derive = { workspace = true }
trezoa-program-runtime = { workspace = true }
trezoa-sdk = { workspace = true }

[dev-dependencies]
trezoa-logger = { workspace = true }

[lib]
crate-type = ["lib"]
name = "trezoa_config_program"

[package.metadata.docs.rs]
targets = ["x86_64-unknown-linux-gnu"]
