[package]
name = "trezoa-sbf-rust-realloc"
documentation = "https://docs.rs/trezoa-sbf-rust-realloc"
version = { workspace = true }
description = { workspace = true }
authors = { workspace = true }
repository = { workspace = true }
homepage = { workspace = true }
license = { workspace = true }
edition = { workspace = true }

[features]
default = ["program"]
program = []

[dependencies]
trezoa-program = { workspace = true }

[lib]
crate-type = ["lib", "cdylib"]

[package.metadata.docs.rs]
targets = ["x86_64-unknown-linux-gnu"]
