[package]
name = "trezoa-remote-wallet"
documentation = "https://docs.rs/trezoa-remote-wallet"
version = { workspace = true }
authors = { workspace = true }
description = { workspace = true }
repository = { workspace = true }
homepage = { workspace = true }
license = { workspace = true }
edition = { workspace = true }

[package.metadata.docs.rs]
targets = ["x86_64-unknown-linux-gnu"]

[features]
default = ["linux-static-hidraw"]
trezoa-unstable-api = []
linux-shared-hidraw = ["hidapi/linux-shared-hidraw"]
linux-shared-libusb = ["hidapi/linux-shared-libusb"]
linux-static-hidraw = ["hidapi/linux-static-hidraw"]
linux-static-libusb = ["hidapi/linux-static-libusb"]

[dependencies]
console = { workspace = true }
dialoguer = { workspace = true }
hidapi = { workspace = true, optional = true }
log = { workspace = true }
num-derive = { workspace = true }
num-traits = { workspace = true }
parking_lot = { workspace = true }
qstring = { workspace = true }
semver = { workspace = true }
trezoa-derivation-path = { workspace = true }
trezoa-offchain-message = { workspace = true }
trezoa-pubkey = { workspace = true, features = ["std"] }
trezoa-signature = { workspace = true, features = ["std"] }
trezoa-signer = { workspace = true }
thiserror = { workspace = true }
trezor-client = { workspace = true }
uriparse = { workspace = true }

[dev-dependencies]
assert_matches = { workspace = true }
serial_test = { workspace = true }
trezoa-pubkey = { workspace = true, features = ["rand"] }
