[package]
name = "trezoa-local-cluster"
description = "Blockchain, Rebuilt for Scale"
documentation = "https://docs.rs/trezoa-local-cluster"
version = { workspace = true }
authors = { workspace = true }
repository = { workspace = true }
homepage = { workspace = true }
license = { workspace = true }
edition = { workspace = true }

[dependencies]
crossbeam-channel = { workspace = true }
itertools = { workspace = true }
log = { workspace = true }
rand = { workspace = true }
rayon = { workspace = true }
trezoa-accounts-db = { workspace = true }
trezoa-client = { workspace = true }
trezoa-config-program = { workspace = true }
trezoa-core = { workspace = true }
trezoa-entry = { workspace = true }
trezoa-gossip = { workspace = true }
trezoa-ledger = { workspace = true }
trezoa-logger = { workspace = true }
trezoa-pubsub-client = { workspace = true }
trezoa-rpc-client = { workspace = true }
trezoa-rpc-client-api = { workspace = true }
trezoa-runtime = { workspace = true }
trezoa-sdk = { workspace = true }
trezoa-stake-program = { workspace = true }
trezoa-streamer = { workspace = true }
trezoa-thin-client = { workspace = true }
trezoa-tpu-client = { workspace = true }
trezoa-turbine = { workspace = true }
trezoa-vote = { workspace = true }
trezoa-vote-program = { workspace = true }
static_assertions = { workspace = true }
tempfile = { workspace = true }
trees = { workspace = true }

[dev-dependencies]
assert_matches = { workspace = true }
fs_extra = { workspace = true }
gag = { workspace = true }
serial_test = { workspace = true }
trezoa-download-utils = { workspace = true }
trezoa-ledger = { workspace = true, features = ["dev-context-only-utils"] }

[package.metadata.docs.rs]
targets = ["x86_64-unknown-linux-gnu"]
