[package]
name = "trezoa-local-cluster"
documentation = "https://docs.rs/trezoa-local-cluster"
version = { workspace = true }
authors = { workspace = true }
description = { workspace = true }
repository = { workspace = true }
homepage = { workspace = true }
license = { workspace = true }
edition = { workspace = true }

[package.metadata.docs.rs]
targets = ["x86_64-unknown-linux-gnu"]

[features]
trezoa-unstable-api = []
dev-context-only-utils = ["trezoa-core/dev-context-only-utils"]

[dependencies]
trezoa-feature-set = { workspace = true }
trezoa-logger = { workspace = true }
trezoa-snapshots = { workspace = true }
crossbeam-channel = { workspace = true }
itertools = { workspace = true }
log = { workspace = true }
rand = { workspace = true }
rayon = { workspace = true }
trezoa-account = { workspace = true }
trezoa-accounts-db = { workspace = true }
trezoa-client = { workspace = true }
trezoa-client-traits = { workspace = true }
trezoa-clock = { workspace = true }
trezoa-cluster-type = { workspace = true }
trezoa-commitment-config = { workspace = true }
trezoa-core = { workspace = true }
trezoa-entry = { workspace = true }
trezoa-epoch-schedule = { workspace = true }
trezoa-genesis-config = { workspace = true }
trezoa-gossip = { workspace = true }
trezoa-hard-forks = { workspace = true }
trezoa-hash = { workspace = true }
trezoa-keypair = { workspace = true }
trezoa-ledger = { workspace = true }
trezoa-message = { workspace = true }
trezoa-native-token = { workspace = true }
trezoa-net-utils = { workspace = true }
trezoa-poh-config = { workspace = true }
trezoa-program-binaries = { workspace = true }
trezoa-pubkey = { workspace = true }
trezoa-pubsub-client = { workspace = true }
trezoa-quic-client = { workspace = true }
trezoa-rent = { workspace = true }
trezoa-rpc-client = { workspace = true }
trezoa-rpc-client-api = { workspace = true }
trezoa-runtime = { workspace = true }
trezoa-sdk-ids = { workspace = true }
trezoa-shred-version = { workspace = true }
trezoa-signer = { workspace = true }
trezoa-slot-hashes = { workspace = true }
trezoa-stake-interface = { workspace = true }
trezoa-streamer = { workspace = true }
trezoa-system-interface = { workspace = true }
trezoa-system-transaction = { workspace = true }
trezoa-time-utils = { workspace = true }
trezoa-tpu-client = { workspace = true }
trezoa-transaction = { workspace = true }
trezoa-transaction-error = { workspace = true }
trezoa-turbine = { workspace = true }
trezoa-validator-exit = { workspace = true }
trezoa-vote = { workspace = true }
trezoa-vote-interface = { workspace = true }
trezoa-vote-program = { workspace = true }
static_assertions = { workspace = true }
strum = { workspace = true, features = ["derive"] }
tempfile = { workspace = true }
trees = { workspace = true }

[dev-dependencies]
assert_matches = { workspace = true }
fs_extra = { workspace = true }
gag = { workspace = true }
serial_test = { workspace = true }
trezoa-core = { workspace = true, features = ["dev-context-only-utils"] }
trezoa-download-utils = { workspace = true }
trezoa-genesis-utils = { workspace = true }
trezoa-ledger = { workspace = true, features = ["dev-context-only-utils"] }
trezoa-local-cluster = { path = ".", features = ["trezoa-unstable-api", "dev-context-only-utils"] }
trezoa-runtime = { workspace = true, features = ["dev-context-only-utils"] }
