[package]
name = "trezoa-vote"
description = "Trezoa vote"
documentation = "https://docs.rs/trezoa-vote"
version = { workspace = true }
authors = { workspace = true }
repository = { workspace = true }
homepage = { workspace = true }
license = { workspace = true }
edition = { workspace = true }

[package.metadata.docs.rs]
targets = ["x86_64-unknown-linux-gnu"]

[lib]
crate-type = ["lib"]
name = "trezoa_vote"

[features]
trezoa-unstable-api = []
dev-context-only-utils = ["dep:rand", "dep:bincode"]
frozen-abi = [
    "dep:trezoa-frozen-abi",
    "dep:trezoa-frozen-abi-macro",
    "trezoa-vote-interface/frozen-abi",
]

[dependencies]
bincode = { workspace = true, optional = true }
itertools = { workspace = true }
log = { workspace = true }
rand = { version = "0.9.2", optional = true }
serde = { workspace = true, features = ["rc"] }
trezoa-account = { workspace = true, features = ["bincode"] }
trezoa-bincode = { workspace = true }
trezoa-clock = { workspace = true }
trezoa-frozen-abi = { workspace = true, optional = true, features = [
    "frozen-abi",
] }
trezoa-frozen-abi-macro = { workspace = true, optional = true, features = [
    "frozen-abi",
] }
trezoa-hash = { workspace = true }
trezoa-instruction = { workspace = true }
trezoa-keypair = { workspace = true }
trezoa-packet = { workspace = true }
trezoa-pubkey = { workspace = true }
trezoa-sdk-ids = { workspace = true }
trezoa-serialize-utils = { workspace = true }
trezoa-signature = { workspace = true }
trezoa-signer = { workspace = true }
trezoa-svm-transaction = { workspace = true }
trezoa-transaction = { workspace = true, features = ["bincode"] }
trezoa-vote-interface = { workspace = true, features = ["bincode"] }
thiserror = { workspace = true }

[dev-dependencies]
trezoa-logger = { workspace = true }
arbitrary = { workspace = true }
bencher = { workspace = true }
bincode = { workspace = true }
rand = { workspace = true }
trezoa-keypair = { workspace = true }
trezoa-sha256-hasher = { workspace = true }
trezoa-signer = { workspace = true }
trezoa-transaction = { workspace = true, features = ["bincode"] }
trezoa-vote = { path = ".", features = ["trezoa-unstable-api"] }
trezoa-vote-interface = { workspace = true, features = ["bincode", "dev-context-only-utils"] }
static_assertions = { workspace = true }

[[bench]]
name = "vote_account"
harness = false

[lints]
workspace = true
