[package]
name = "trezoa-xdp"
description = "Trezoa-team XDP implementation"
version = { workspace = true }
repository = { workspace = true }
homepage = { workspace = true }
license = { workspace = true }
edition = { workspace = true }
publish = true

[features]
trezoa-unstable-api = []

[dependencies]
arc-swap = { workspace = true }
crossbeam-channel = { workspace = true }
libc = { workspace = true }
log = { workspace = true }
thiserror = { workspace = true }

[target.'cfg(target_os = "linux")'.dependencies]
trezoa-xdp-ebpf = { workspace = true }
aya = { workspace = true }
caps = { workspace = true }
