[package]
name = "trezoa-sbf-rust-simulation"
description = "Trezoa SBF Program Simulation Differences"
documentation = "https://docs.rs/trezoa-sbf-rust-simulation"
version = { workspace = true }
authors = { workspace = true }
repository = { workspace = true }
homepage = { workspace = true }
license = { workspace = true }
edition = { workspace = true }

[features]
test-bpf = []

[dependencies]
trezoa-program = { workspace = true }

[dev-dependencies]
trezoa-validator = { workspace = true }
trezoa-logger = { workspace = true }
trezoa-program-test = { workspace = true }
trezoa-sdk = { workspace = true }

[lib]
crate-type = ["cdylib", "lib"]

[package.metadata.docs.rs]
targets = ["x86_64-unknown-linux-gnu"]
