[package]
name = "trezoa-bpf-loader-program"
description = "Trezoa BPF loader"
documentation = "https://docs.rs/trezoa-bpf-loader-program"
version = { workspace = true }
authors = { workspace = true }
repository = { workspace = true }
homepage = { workspace = true }
license = { workspace = true }
edition = { workspace = true }

[dependencies]
bincode = { workspace = true }
byteorder = { workspace = true }
libsecp256k1 = { workspace = true }
log = { workspace = true }
scopeguard = { workspace = true }
trezoa-measure = { workspace = true }
trezoa-program-runtime = { workspace = true }
trezoa-sdk = { workspace = true }
trezoa-zk-token-sdk = { workspace = true }
trezoa_rbpf = { workspace = true }
thiserror = { workspace = true }

[dev-dependencies]
assert_matches = { workspace = true }
memoffset = { workspace = true }
rand = { workspace = true }
trezoa-sdk = { workspace = true, features = ["dev-context-only-utils"] }
test-case = { workspace = true }

[lib]
crate-type = ["lib"]
name = "trezoa_bpf_loader_program"

[package.metadata.docs.rs]
targets = ["x86_64-unknown-linux-gnu"]
