[package]
name = "trezoa-stake-program"
description = "Trezoa Stake program"
documentation = "https://docs.rs/trezoa-stake-program"
version = { workspace = true }
authors = { workspace = true }
repository = { workspace = true }
homepage = { workspace = true }
license = { workspace = true }
edition = { workspace = true }

[dependencies]
bincode = { workspace = true }
log = { workspace = true }
trezoa-config-program = { workspace = true }
trezoa-program-runtime = { workspace = true }
trezoa-sdk = { workspace = true }
trezoa-vote-program = { workspace = true }

[dev-dependencies]
assert_matches = { workspace = true }
proptest = { workspace = true }
trezoa-logger = { workspace = true }
test-case = { workspace = true }

[build-dependencies]
rustc_version = { workspace = true }

[lib]
crate-type = ["lib"]
name = "trezoa_stake_program"

[package.metadata.docs.rs]
targets = ["x86_64-unknown-linux-gnu"]
