[package]
name = "trezoa-precompiles"
description = "Trezoa precompiled programs."
documentation = "https://docs.rs/trezoa-precompiles"
version = { workspace = true }
authors = { workspace = true }
repository = { workspace = true }
homepage = { workspace = true }
license = { workspace = true }
edition = { workspace = true }

[package.metadata.docs.rs]
targets = ["x86_64-unknown-linux-gnu"]
all-features = true
rustdoc-args = ["--cfg=docsrs"]

[features]
trezoa-unstable-api = []

[dependencies]
trezoa-feature-set = { workspace = true }
bincode = { workspace = true }
digest = { workspace = true }
ed25519-dalek = { workspace = true }
libsecp256k1 = { workspace = true, features = ["hmac"] }
openssl = { workspace = true }
sha3 = { workspace = true }
trezoa-ed25519-program = { workspace = true }
trezoa-message = { workspace = true }
trezoa-precompile-error = { workspace = true }
trezoa-pubkey = { workspace = true }
trezoa-sdk-ids = { workspace = true }
trezoa-secp256k1-program = { workspace = true, features = ["serde"] }
trezoa-secp256r1-program = { workspace = true, features = ["openssl-vendored"] }

[dev-dependencies]
trezoa-logger = { workspace = true }
trezoa-precompiles = { path = ".", features = ["trezoa-unstable-api"] }
bytemuck = { workspace = true }
hex = { workspace = true }
rand0-7 = { workspace = true }
trezoa-instruction = { workspace = true }
trezoa-keccak-hasher = { workspace = true, features = ["sha3"] }
trezoa-secp256k1-program = { workspace = true, features = ["bincode"] }

[lints]
workspace = true
