[package]
name = "trezoa-rpc-client-api"
description = "Trezoa Client Common Utilities"
documentation = "https://docs.rs/trezoa-rpc-client-api"
version = { workspace = true }
authors = { workspace = true }
repository = { workspace = true }
homepage = { workspace = true }
license = { workspace = true }
edition = { workspace = true }

[package.metadata.docs.rs]
targets = ["x86_64-unknown-linux-gnu"]

[features]
trezoa-unstable-api = []

[dependencies]
anyhow = { workspace = true }
jsonrpc-core = { workspace = true }
reqwest = { workspace = true, default-features = false, features = ["rustls-tls"] }
reqwest-middleware = { workspace = true }
serde = { workspace = true }
serde_json = { workspace = true }
trezoa-account-decoder-client-types = { workspace = true }
trezoa-clock = { workspace = true }
trezoa-rpc-client-types = { workspace = true }
trezoa-signer = { workspace = true }
trezoa-transaction-error = { workspace = true }
trezoa-transaction-status-client-types = { workspace = true }
thiserror = { workspace = true }

[dev-dependencies]
test-case = { workspace = true }
