[package]
name = "trezoa-svm-test-harness"
description = "Trezoa SVM test harness."
documentation = "https://docs.rs/trezoa-svm-test-harness"
version = { workspace = true }
authors = { workspace = true }
repository = { workspace = true }
homepage = { workspace = true }
license = { workspace = true }
edition = { workspace = true }
publish = false

[[bin]]
name = "test_exec_instr"
path = "bin/test_exec_instr.rs"
required-features = ["fuzz"]

[features]
trezoa-unstable-api = []
dummy-for-ci-check = ["fuzz"]
fuzz = [
    "dep:clap",
    "dep:prost",
    "trezoa-svm-test-harness-fixture/fuzz",
    "trezoa-svm-test-harness-instr/fuzz",
]

[dependencies]
trezoa-logger = { workspace = true }
clap = { version = "4.5.2", features = ["derive"], optional = true }
prost = { workspace = true, optional = true }
trezoa-svm-test-harness-fixture = { workspace = true }
trezoa-svm-test-harness-instr = { workspace = true }

[lints]
workspace = true
