[package]
name = "trezoa-sbf-rust-many-args-dep"
version = { workspace = true }
description = { workspace = true }
authors = { workspace = true }
repository = { workspace = true }
homepage = { workspace = true }
license = { workspace = true }
edition = { workspace = true }

[dependencies]
trezoa-msg = { workspace = true }
trezoa-program = { workspace = true }
