[package]
name = "trezoa-rpc"
description = "Trezoa RPC"
documentation = "https://docs.rs/trezoa-rpc"
version = { workspace = true }
authors = { workspace = true }
repository = { workspace = true }
homepage = { workspace = true }
license = { workspace = true }
edition = { workspace = true }

[dependencies]
base64 = { workspace = true }
bincode = { workspace = true }
bs58 = { workspace = true }
crossbeam-channel = { workspace = true }
dashmap = { workspace = true }
itertools = { workspace = true }
jsonrpc-core = { workspace = true }
jsonrpc-core-client = { workspace = true }
jsonrpc-derive = { workspace = true }
jsonrpc-http-server = { workspace = true }
jsonrpc-pubsub = { workspace = true }
libc = { workspace = true }
log = { workspace = true }
rayon = { workspace = true }
regex = { workspace = true }
serde = { workspace = true }
serde_derive = { workspace = true }
serde_json = { workspace = true }
soketto = { workspace = true }
trezoa-account-decoder = { workspace = true }
trezoa-accounts-db = { workspace = true }
trezoa-client = { workspace = true }
trezoa-entry = { workspace = true }
trezoa-faucet = { workspace = true }
trezoa-gossip = { workspace = true }
trezoa-ledger = { workspace = true }
trezoa-measure = { workspace = true }
trezoa-metrics = { workspace = true }
trezoa-perf = { workspace = true }
trezoa-poh = { workspace = true }
trezoa-rayon-threadlimit = { workspace = true }
trezoa-rpc-client-api = { workspace = true }
trezoa-runtime = { workspace = true }
trezoa-sdk = { workspace = true }
trezoa-send-transaction-service = { workspace = true }
trezoa-stake-program = { workspace = true }
trezoa-storage-bigtable = { workspace = true }
trezoa-streamer = { workspace = true }
trezoa-tpu-client = { workspace = true }
trezoa-transaction-status = { workspace = true }
trezoa-version = { workspace = true }
trezoa-vote = { workspace = true }
trezoa-vote-program = { workspace = true }
tpl-token = { workspace = true, features = ["no-entrypoint"] }
tpl-token-2022 = { workspace = true, features = ["no-entrypoint"] }
stream-cancel = { workspace = true }
thiserror = { workspace = true }
tokio = { workspace = true, features = ["full"] }
tokio-util = { workspace = true, features = ["codec", "compat"] }

[dev-dependencies]
serial_test = { workspace = true }
trezoa-net-utils = { workspace = true }
trezoa-runtime = { workspace = true, features = ["dev-context-only-utils"] }
trezoa-stake-program = { workspace = true }
tpl-pod = { workspace = true }
symlink = { workspace = true }

[lib]
crate-type = ["lib"]
name = "trezoa_rpc"

[package.metadata.docs.rs]
targets = ["x86_64-unknown-linux-gnu"]
