[package]
name = "trezoa-rpc"
description = "Trezoa RPC"
documentation = "https://docs.rs/trezoa-rpc"
version = { workspace = true }
authors = { workspace = true }
repository = { workspace = true }
homepage = { workspace = true }
license = { workspace = true }
edition = { workspace = true }

[package.metadata.docs.rs]
targets = ["x86_64-unknown-linux-gnu"]

[lib]
crate-type = ["lib"]
name = "trezoa_rpc"

[features]
trezoa-unstable-api = []
dev-context-only-utils = [
    "trezoa-ledger/dev-context-only-utils",
    "trezoa-rpc/dev-context-only-utils",
]

[dependencies]
trezoa-feature-set = { workspace = true }
trezoa-snapshots = { workspace = true }
base64 = { workspace = true }
bincode = { workspace = true }
bs58 = { workspace = true }
crossbeam-channel = { workspace = true }
dashmap = { workspace = true }
itertools = { workspace = true }
jsonrpc-core = { workspace = true }
jsonrpc-core-client = { workspace = true }
jsonrpc-derive = { workspace = true }
jsonrpc-http-server = { workspace = true }
jsonrpc-pubsub = { workspace = true }
libc = { workspace = true }
log = { workspace = true }
rayon = { workspace = true }
regex = { workspace = true }
serde = { workspace = true }
serde_json = { workspace = true }
soketto = { workspace = true }
trezoa-account = { workspace = true }
trezoa-account-decoder = { workspace = true }
trezoa-accounts-db = { workspace = true }
trezoa-cli-output = { workspace = true }
trezoa-client = { workspace = true }
trezoa-clock = { workspace = true }
trezoa-commitment-config = { workspace = true }
trezoa-entry = { workspace = true }
trezoa-epoch-info = { workspace = true }
trezoa-epoch-rewards-hasher = { workspace = true }
trezoa-epoch-schedule = { workspace = true }
trezoa-faucet = { workspace = true }
trezoa-genesis-config = { workspace = true }
trezoa-gossip = { workspace = true }
trezoa-hash = { workspace = true }
trezoa-keypair = { workspace = true }
trezoa-ledger = { workspace = true }
trezoa-measure = { workspace = true }
trezoa-message = { workspace = true }
trezoa-metrics = { workspace = true }
trezoa-native-token = { workspace = true }
trezoa-perf = { workspace = true }
trezoa-poh = { workspace = true }
trezoa-poh-config = { workspace = true }
trezoa-program-pack = { workspace = true }
trezoa-pubkey = { workspace = true }
trezoa-quic-definitions = { workspace = true }
trezoa-rayon-threadlimit = { workspace = true }
trezoa-rpc-client-api = { workspace = true }
trezoa-runtime = { workspace = true }
trezoa-runtime-transaction = { workspace = true }
trezoa-send-transaction-service = { workspace = true }
trezoa-signature = { workspace = true }
trezoa-signer = { workspace = true }
trezoa-slot-history = { workspace = true }
trezoa-storage-bigtable = { workspace = true }
trezoa-svm = { workspace = true }
trezoa-system-interface = { workspace = true }
trezoa-system-transaction = { workspace = true }
trezoa-sysvar = { workspace = true }
trezoa-time-utils = { workspace = true }
trezoa-tpu-client = { workspace = true }
trezoa-transaction = { workspace = true }
trezoa-transaction-context = { workspace = true }
trezoa-transaction-error = { workspace = true }
trezoa-transaction-status = { workspace = true }
trezoa-validator-exit = { workspace = true }
trezoa-version = { workspace = true }
trezoa-vote = { workspace = true }
trezoa-vote-program = { workspace = true }
spl-generic-token = { workspace = true }
tpl-token-2022-interface = { workspace = true }
tpl-token-interface = { workspace = true }
stream-cancel = { workspace = true }
thiserror = { workspace = true }
tokio = { workspace = true, features = ["full"] }
tokio-util = { workspace = true, features = ["codec", "compat"] }

[dev-dependencies]
trezoa-reserved-account-keys = { workspace = true }
serial_test = { workspace = true }
trezoa-address-lookup-table-interface = { workspace = true }
trezoa-cluster-type = { workspace = true }
trezoa-compute-budget-interface = { workspace = true }
trezoa-fee-calculator = { workspace = true }
trezoa-fee-structure = { workspace = true }
trezoa-instruction = { workspace = true }
trezoa-net-utils = { workspace = true }
trezoa-nonce = { workspace = true }
trezoa-nonce-account = { workspace = true }
trezoa-program-option = { workspace = true }
trezoa-program-runtime = { workspace = true }
trezoa-rent = { workspace = true }
trezoa-rpc = { path = ".", features = ["dev-context-only-utils"] }
trezoa-runtime = { workspace = true, features = ["dev-context-only-utils"] }
trezoa-runtime-transaction = { workspace = true, features = [
    "dev-context-only-utils",
] }
trezoa-sdk-ids = { workspace = true }
trezoa-send-transaction-service = { workspace = true, features = ["dev-context-only-utils"] }
trezoa-sha256-hasher = { workspace = true }
trezoa-stake-interface = { workspace = true }
trezoa-svm-log-collector = { workspace = true }
trezoa-vote-interface = { workspace = true }
spl-pod = { workspace = true }
symlink = { workspace = true }
test-case = { workspace = true }
