[package]
name = "trezoa-reserved-account-keys"
description = "Reserved Trezoa account keys"
documentation = "https://docs.rs/trezoa-reserved-account-keys"
version = { workspace = true }
authors = { workspace = true }
repository = { workspace = true }
homepage = { workspace = true }
license = { workspace = true }
edition = { workspace = true }

[package.metadata.docs.rs]
targets = ["x86_64-unknown-linux-gnu"]
all-features = true
rustdoc-args = ["--cfg=docsrs"]

[features]
trezoa-unstable-api = []
frozen-abi = ["dep:trezoa-frozen-abi", "dep:trezoa-frozen-abi-macro"]

[dependencies]
trezoa-feature-set = { workspace = true }
trezoa-frozen-abi = { workspace = true, optional = true, features = [
    "frozen-abi",
] }
trezoa-frozen-abi-macro = { workspace = true, optional = true, features = [
    "frozen-abi",
] }
trezoa-pubkey = { workspace = true, default-features = false }
trezoa-sdk-ids = { workspace = true }

[dev-dependencies]
trezoa-message = { workspace = true }
trezoa-pubkey = { workspace = true, default-features = false, features = ["std"] }
trezoa-sysvar = { workspace = true }

[lints]
workspace = true
