[package]
name = "trezoa-geyser-plugin-manager"
description = "The Trezoa Geyser plugin manager."
documentation = "https://docs.rs/trezoa-geyser-plugin-manager"
version = { workspace = true }
authors = { workspace = true }
repository = { workspace = true }
homepage = { workspace = true }
license = { workspace = true }
edition = { workspace = true }

[package.metadata.docs.rs]
targets = ["x86_64-unknown-linux-gnu"]

[features]
trezoa-unstable-api = []

[dependencies]
trezoa-geyser-plugin-interface = { workspace = true }
bs58 = { workspace = true }
crossbeam-channel = { workspace = true }
json5 = { workspace = true }
jsonrpc-core = { workspace = true }
libloading = { workspace = true }
log = { workspace = true }
serde_json = { workspace = true }
trezoa-account = { workspace = true }
trezoa-accounts-db = { workspace = true }
trezoa-clock = { workspace = true }
trezoa-entry = { workspace = true }
trezoa-hash = { workspace = true }
trezoa-ledger = { workspace = true }
trezoa-pubkey = { workspace = true }
trezoa-rpc = { workspace = true }
trezoa-runtime = { workspace = true }
trezoa-signature = { workspace = true }
trezoa-transaction = { workspace = true }
trezoa-transaction-status = { workspace = true }
thiserror = { workspace = true }
tokio = { workspace = true }
