[package]
name = "trezoa-transaction-dos"
publish = false
version = { workspace = true }
authors = { workspace = true }
repository = { workspace = true }
homepage = { workspace = true }
license = { workspace = true }
edition = { workspace = true }

[dependencies]
bincode = { workspace = true }
clap = { workspace = true }
log = { workspace = true }
rand = { workspace = true }
rayon = { workspace = true }
trezoa-clap-utils = { workspace = true }
trezoa-cli = { workspace = true }
trezoa-client = { workspace = true }
trezoa-core = { workspace = true }
trezoa-faucet = { workspace = true }
trezoa-gossip = { workspace = true }
trezoa-logger = { workspace = true }
trezoa-measure = { workspace = true }
trezoa-net-utils = { workspace = true }
trezoa-rpc-client = { workspace = true }
trezoa-runtime = { workspace = true }
trezoa-sdk = { workspace = true }
trezoa-streamer = { workspace = true }
trezoa-transaction-status = { workspace = true }
trezoa-version = { workspace = true }

[dev-dependencies]
trezoa-local-cluster = { workspace = true }

[package.metadata.docs.rs]
targets = ["x86_64-unknown-linux-gnu"]
