[package]
name = "trezoa-thin-client"
description = "Trezoa Thin Client"
documentation = "https://docs.rs/trezoa-thin-client"
version = { workspace = true }
authors = { workspace = true }
repository = { workspace = true }
homepage = { workspace = true }
license = { workspace = true }
edition = { workspace = true }

[dependencies]
bincode = { workspace = true }
log = { workspace = true }
rayon = { workspace = true }
trezoa-connection-cache = { workspace = true }
trezoa-rpc-client = { workspace = true }
trezoa-rpc-client-api = { workspace = true }
trezoa-sdk = { workspace = true }

[dev-dependencies]
trezoa-logger = { workspace = true }

[package.metadata.docs.rs]
targets = ["x86_64-unknown-linux-gnu"]
