[package]
name = "trezoa-entry"
description = "Trezoa Entry"
documentation = "https://docs.rs/trezoa-poh"
version = { workspace = true }
authors = { workspace = true }
repository = { workspace = true }
homepage = { workspace = true }
license = { workspace = true }
edition = { workspace = true }

[package.metadata.docs.rs]
targets = ["x86_64-unknown-linux-gnu"]

[lib]
crate-type = ["lib"]
name = "trezoa_entry"

[features]
trezoa-unstable-api = []
dev-context-only-utils = []

[dependencies]
bincode = { workspace = true }
crossbeam-channel = { workspace = true }
dlopen2 = { workspace = true }
log = { workspace = true }
num_cpus = { workspace = true }
rayon = { workspace = true }
serde = { workspace = true }
trezoa-address = { workspace = true }
trezoa-hash = { workspace = true }
trezoa-measure = { workspace = true }
trezoa-merkle-tree = { workspace = true }
trezoa-message = { workspace = true }
trezoa-metrics = { workspace = true }
trezoa-packet = { workspace = true }
trezoa-perf = { workspace = true }
trezoa-runtime-transaction = { workspace = true }
trezoa-sha256-hasher = { workspace = true }
trezoa-short-vec = { workspace = true }
trezoa-signature = { workspace = true }
trezoa-transaction = { workspace = true }
trezoa-transaction-error = { workspace = true }
wincode = { workspace = true }

[dev-dependencies]
trezoa-logger = { workspace = true }
trezoa-reserved-account-keys = { workspace = true }
assert_matches = { workspace = true }
proptest = { workspace = true }
rand = { workspace = true }
trezoa-entry = { path = ".", features = ["trezoa-unstable-api", "dev-context-only-utils"] }
trezoa-keypair = { workspace = true }
trezoa-message = { workspace = true }
trezoa-perf = { workspace = true, features = ["dev-context-only-utils"] }
trezoa-pubkey = { workspace = true }
trezoa-signature = { workspace = true }
trezoa-signer = { workspace = true }
trezoa-system-transaction = { workspace = true }
trezoa-transaction = { workspace = true, features = ["verify"] }

[[bench]]
name = "entry_sigverify"
