[package]
name = "trezoa-entry"
description = "Trezoa Entry"
documentation = "https://docs.rs/trezoa-poh"
version = { workspace = true }
authors = { workspace = true }
repository = { workspace = true }
homepage = { workspace = true }
license = { workspace = true }
edition = { workspace = true }

[dependencies]
bincode = { workspace = true }
crossbeam-channel = { workspace = true }
dlopen2 = { workspace = true }
lazy_static = { workspace = true }
log = { workspace = true }
rand = { workspace = true }
rayon = { workspace = true }
serde = { workspace = true }
trezoa-measure = { workspace = true }
trezoa-merkle-tree = { workspace = true }
trezoa-metrics = { workspace = true }
trezoa-perf = { workspace = true }
trezoa-rayon-threadlimit = { workspace = true }
trezoa-sdk = { workspace = true }

[dev-dependencies]
assert_matches = { workspace = true }
trezoa-logger = { workspace = true }

[lib]
crate-type = ["lib"]
name = "trezoa_entry"

[[bench]]
name = "entry_sigverify"

[package.metadata.docs.rs]
targets = ["x86_64-unknown-linux-gnu"]
