[package]
name = "trezoa-validator"
description = "Blockchain, Rebuilt for Scale"
documentation = "https://docs.rs/trezoa-validator"
default-run = "trezoa-validator"
version = { workspace = true }
authors = { workspace = true }
repository = { workspace = true }
homepage = { workspace = true }
license = { workspace = true }
edition = { workspace = true }

[dependencies]
trezoa-geyser-plugin-interface = { workspace = true }
chrono = { workspace = true, features = ["default", "serde"] }
clap = { workspace = true }
console = { workspace = true }
core_affinity = { workspace = true }
crossbeam-channel = { workspace = true }
fd-lock = { workspace = true }
indicatif = { workspace = true }
itertools = { workspace = true }
jsonrpc-core = { workspace = true }
jsonrpc-core-client = { workspace = true, features = ["ipc"] }
jsonrpc-derive = { workspace = true }
jsonrpc-ipc-server = { workspace = true }
jsonrpc-server-utils = { workspace = true }
lazy_static = { workspace = true }
libloading = { workspace = true }
log = { workspace = true }
num_cpus = { workspace = true }
rand = { workspace = true }
rayon = { workspace = true }
serde = { workspace = true }
serde_json = { workspace = true }
serde_yaml = { workspace = true }
trezoa-accounts-db = { workspace = true }
trezoa-clap-utils = { workspace = true }
trezoa-cli-config = { workspace = true }
trezoa-core = { workspace = true }
trezoa-download-utils = { workspace = true }
trezoa-entry = { workspace = true }
trezoa-faucet = { workspace = true }
trezoa-genesis-utils = { workspace = true }
trezoa-geyser-plugin-manager = { workspace = true }
trezoa-gossip = { workspace = true }
trezoa-ledger = { workspace = true }
trezoa-logger = { workspace = true }
trezoa-metrics = { workspace = true }
trezoa-net-utils = { workspace = true }
trezoa-perf = { workspace = true }
trezoa-poh = { workspace = true }
trezoa-rpc = { workspace = true }
trezoa-rpc-client = { workspace = true }
trezoa-rpc-client-api = { workspace = true }
trezoa-runtime = { workspace = true }
trezoa-sdk = { workspace = true }
trezoa-send-transaction-service = { workspace = true }
trezoa-storage-bigtable = { workspace = true }
trezoa-streamer = { workspace = true }
trezoa-test-validator = { workspace = true }
trezoa-tpu-client = { workspace = true }
trezoa-version = { workspace = true }
trezoa-vote-program = { workspace = true }
symlink = { workspace = true }
thiserror = { workspace = true }

[dev-dependencies]
trezoa-account-decoder = { workspace = true }
trezoa-runtime = { workspace = true, features = ["dev-context-only-utils"] }
tpl-token-2022 = { workspace = true, features = ["no-entrypoint"] }

[target.'cfg(not(target_env = "msvc"))'.dependencies]
jemallocator = { workspace = true }

[target."cfg(unix)".dependencies]
libc = { workspace = true }
signal-hook = { workspace = true }

[package.metadata.docs.rs]
targets = ["x86_64-unknown-linux-gnu"]
