[package]
name = "trezoa-syscalls"
description = "Trezoa-team implementation of the Trezoa syscalls."
documentation = "https://docs.rs/trezoa-syscalls"
version = { workspace = true }
authors = { workspace = true }
repository = { workspace = true }
homepage = { workspace = true }
license = { workspace = true }
edition = { workspace = true }

[package.metadata.docs.rs]
targets = ["x86_64-unknown-linux-gnu"]

[features]
default = ["metrics"]
trezoa-unstable-api = []
metrics = ["trezoa-program-runtime/metrics"]
shuttle-test = [
    "trezoa-program-runtime/shuttle-test",
    "trezoa-sbpf/shuttle-test",
    "trezoa-svm-type-overrides/shuttle-test",
]
svm-internal = []

[dependencies]
bincode = { workspace = true }
libsecp256k1 = { workspace = true }
num-traits = { workspace = true }
trezoa-account = { workspace = true }
trezoa-account-info = { workspace = true }
trezoa-big-mod-exp = { workspace = true }
trezoa-blake3-hasher = { workspace = true, features = ["blake3"] }
trezoa-bn254 = { workspace = true }
trezoa-clock = { workspace = true }
trezoa-cpi = { workspace = true }
trezoa-curve25519 = { workspace = true }
trezoa-hash = { workspace = true }
trezoa-instruction = { workspace = true }
trezoa-keccak-hasher = { workspace = true, features = ["sha3"] }
trezoa-loader-v3-interface = { workspace = true, features = ["serde"] }
trezoa-poseidon = { workspace = true }
trezoa-program-entrypoint = { workspace = true }
trezoa-program-runtime = { workspace = true }
trezoa-pubkey = { workspace = true }
trezoa-sbpf = { workspace = true, features = ["jit"] }
trezoa-sdk-ids = { workspace = true }
trezoa-secp256k1-recover = { workspace = true }
trezoa-sha256-hasher = { workspace = true }
trezoa-stable-layout = { workspace = true }
trezoa-stake-interface = { workspace = true }
trezoa-svm-callback = { workspace = true }
trezoa-svm-feature-set = { workspace = true }
trezoa-svm-log-collector = { workspace = true }
trezoa-svm-measure = { workspace = true }
trezoa-svm-timings = { workspace = true }
trezoa-svm-type-overrides = { workspace = true }
trezoa-sysvar = { workspace = true }
trezoa-sysvar-id = { workspace = true }
trezoa-transaction-context = { workspace = true, features = ["bincode"] }
thiserror = { workspace = true }

[dev-dependencies]
assert_matches = { workspace = true }
trezoa-epoch-rewards = { workspace = true }
trezoa-epoch-schedule = { workspace = true }
trezoa-fee-calculator = { workspace = true }
trezoa-last-restart-slot = { workspace = true }
trezoa-program = { workspace = true }
trezoa-program-runtime = { workspace = true, features = ["dev-context-only-utils"] }
trezoa-pubkey = { workspace = true, features = ["rand"] }
trezoa-rent = { workspace = true }
trezoa-slot-hashes = { workspace = true }
trezoa-transaction-context = { workspace = true, features = ["dev-context-only-utils"] }
static_assertions = { workspace = true }
test-case = { workspace = true }

[lints]
workspace = true
