[package]
name = "trezoa-merkle-tree"
description = "Trezoa Merkle Tree"
documentation = "https://docs.rs/trezoa-merkle-tree"
version = { workspace = true }
authors = { workspace = true }
repository = { workspace = true }
homepage = { workspace = true }
license = { workspace = true }
edition = { workspace = true }

[dependencies]
fast-math = { workspace = true }
trezoa-program = { workspace = true }

[dev-dependencies]
hex = { workspace = true }

[lib]
crate-type = ["lib"]
name = "trezoa_merkle_tree"

[package.metadata.docs.rs]
targets = ["x86_64-unknown-linux-gnu"]
