[package]
name = "trezoa-zk-elgamal-proof-program-tests"
publish = false
version = { workspace = true }
authors = { workspace = true }
repository = { workspace = true }
license = { workspace = true }
edition = { workspace = true }

[features]
trezoa-unstable-api = []

[dev-dependencies]
bytemuck = { workspace = true }
trezoa-account = { workspace = true }
trezoa-compute-budget = { workspace = true }
trezoa-compute-budget-interface = { workspace = true }
trezoa-instruction = { workspace = true }
trezoa-keypair = { workspace = true }
trezoa-program-test = { workspace = true }
trezoa-pubkey = { workspace = true }
trezoa-signer = { workspace = true }
trezoa-system-interface = { workspace = true }
trezoa-transaction = { workspace = true }
trezoa-transaction-error = { workspace = true }
trezoa-zk-sdk = { workspace = true }
