[package]
name = "trezoa-address-lookup-table-program"
description = "Trezoa address lookup table program"
documentation = "https://docs.rs/trezoa-address-loookup-table-program"
version = { workspace = true }
authors = { workspace = true }
repository = { workspace = true }
homepage = { workspace = true }
license = { workspace = true }
edition = { workspace = true }

[dependencies]
bincode = { workspace = true }
bytemuck = { workspace = true }
log = { workspace = true }
num-derive = { workspace = true }
num-traits = { workspace = true }
serde = { workspace = true, features = ["derive"] }
trezoa-frozen-abi = { workspace = true }
trezoa-frozen-abi-macro = { workspace = true }
trezoa-program = { workspace = true }
thiserror = { workspace = true }

[target.'cfg(not(target_os = "trezoa"))'.dependencies]
trezoa-program-runtime = { workspace = true }
trezoa-sdk = { workspace = true }

[build-dependencies]
rustc_version = { workspace = true }

[lib]
crate-type = ["lib"]
name = "trezoa_address_lookup_table_program"

[package.metadata.docs.rs]
targets = ["x86_64-unknown-linux-gnu"]
