[package]
name = "trezoa-tps-client"
version = { workspace = true }
authors = { workspace = true }
description = { workspace = true }
repository = { workspace = true }
homepage = { workspace = true }
license = { workspace = true }
edition = { workspace = true }

[package.metadata.docs.rs]
targets = ["x86_64-unknown-linux-gnu"]
all-features = true
rustdoc-args = ["--cfg=docsrs"]

[features]
trezoa-unstable-api = []
bank-client = ["dep:trezoa-client-traits", "dep:trezoa-runtime"]
dev-context-only-utils = []

[dependencies]
log = { workspace = true }
trezoa-account = { workspace = true }
trezoa-client = { workspace = true }
trezoa-client-traits = { workspace = true, optional = true }
trezoa-clock = { workspace = true }
trezoa-commitment-config = { workspace = true }
trezoa-connection-cache = { workspace = true }
trezoa-epoch-info = { workspace = true }
trezoa-hash = { workspace = true }
trezoa-keypair = { workspace = true }
trezoa-message = { workspace = true }
trezoa-net-utils = { workspace = true }
trezoa-pubkey = { workspace = true }
trezoa-quic-client = { workspace = true }
trezoa-rpc-client = { workspace = true }
trezoa-rpc-client-api = { workspace = true }
trezoa-runtime = { workspace = true, optional = true }
trezoa-signature = { workspace = true }
trezoa-signer = { workspace = true }
trezoa-streamer = { workspace = true }
trezoa-tpu-client = { workspace = true }
trezoa-transaction = { workspace = true }
trezoa-transaction-error = { workspace = true }
trezoa-transaction-status = { workspace = true }
thiserror = { workspace = true }

[dev-dependencies]
trezoa-runtime = { workspace = true, features = ["dev-context-only-utils"] }
tempfile = { workspace = true }
