[package]
name = "trezoa-gossip"
documentation = "https://docs.rs/trezoa-gossip"
version = { workspace = true }
authors = { workspace = true }
description = { workspace = true }
repository = { workspace = true }
homepage = { workspace = true }
license = { workspace = true }
edition = { workspace = true }

[package.metadata.docs.rs]
targets = ["x86_64-unknown-linux-gnu"]

[lib]
bench = false

[features]
frozen-abi = [
    "dep:trezoa-frozen-abi",
    "dep:trezoa-frozen-abi-macro",
    "trezoa-bloom/frozen-abi",
    "trezoa-ledger/frozen-abi",
    "trezoa-perf/frozen-abi",
    "trezoa-runtime/frozen-abi",
    "trezoa-short-vec/frozen-abi",
    "trezoa-version/frozen-abi",
    "trezoa-vote/frozen-abi",
    "trezoa-vote-program/frozen-abi",
]
trezoa-unstable-api = []

[dependencies]
trezoa-feature-set = { workspace = true }
trezoa-logger = { workspace = true }
trezoa-random = { workspace = true }
arc-swap = { workspace = true }
arrayvec = { workspace = true }
assert_matches = { workspace = true }
bincode = { workspace = true }
bv = { workspace = true, features = ["serde"] }
clap = { workspace = true }
crossbeam-channel = { workspace = true }
flate2 = { workspace = true }
indexmap = { workspace = true, features = ["rayon"] }
itertools = { workspace = true }
log = { workspace = true }
lru = { workspace = true }
num-traits = { workspace = true }
rand = { workspace = true }
rand_chacha = { workspace = true }
rayon = { workspace = true }
serde = { workspace = true }
serde-big-array = { workspace = true }
serde_bytes = { workspace = true }
siphasher = { workspace = true }
trezoa-bloom = { workspace = true }
trezoa-clap-utils = { workspace = true }
trezoa-client = { workspace = true }
trezoa-clock = { workspace = true }
trezoa-cluster-type = { workspace = true }
trezoa-connection-cache = { workspace = true }
trezoa-entry = { workspace = true }
trezoa-epoch-schedule = { workspace = true }
trezoa-frozen-abi = { workspace = true, optional = true, features = [
    "frozen-abi",
] }
trezoa-frozen-abi-macro = { workspace = true, optional = true, features = [
    "frozen-abi",
] }
trezoa-hash = { workspace = true }
trezoa-keypair = { workspace = true }
trezoa-ledger = { workspace = true, features = ["trezoa-unstable-api"] }
trezoa-measure = { workspace = true }
trezoa-metrics = { workspace = true }
trezoa-native-token = { workspace = true }
trezoa-net-utils = { workspace = true, features = ["trezoa-unstable-api"] }
trezoa-packet = { workspace = true }
trezoa-perf = { workspace = true }
trezoa-pubkey = { workspace = true, features = ["rand"] }
trezoa-quic-definitions = { workspace = true }
trezoa-rayon-threadlimit = { workspace = true }
trezoa-rpc-client = { workspace = true }
trezoa-runtime = { workspace = true }
trezoa-sanitize = { workspace = true }
trezoa-serde-varint = { workspace = true }
trezoa-sha256-hasher = { workspace = true }
trezoa-short-vec = { workspace = true }
trezoa-signature = { workspace = true, default-features = false }
trezoa-signer = { workspace = true }
trezoa-streamer = { workspace = true }
trezoa-time-utils = { workspace = true }
trezoa-tpu-client = { workspace = true }
trezoa-transaction = { workspace = true }
trezoa-version = { workspace = true }
trezoa-vote = { workspace = true }
trezoa-vote-program = { workspace = true }
static_assertions = { workspace = true }
thiserror = { workspace = true }

[dev-dependencies]
anyhow = { workspace = true }
bs58 = { workspace = true }
criterion = { workspace = true }
num_cpus = { workspace = true }
serial_test = { workspace = true }
trezoa-gossip = { path = ".", features = ["trezoa-unstable-api"] }
trezoa-net-utils = { workspace = true, features = ["dev-context-only-utils"] }
trezoa-perf = { workspace = true, features = ["dev-context-only-utils"] }
trezoa-runtime = { workspace = true, features = ["dev-context-only-utils"] }
trezoa-signature = { workspace = true, features = ["rand"] }
trezoa-system-transaction = { workspace = true }
trezoa-vote-interface = { workspace = true }
static_assertions = { workspace = true }
test-case = { workspace = true }

[[bench]]
name = "crds"
harness = false

[[bench]]
name = "crds_gossip_pull"
harness = false

[[bench]]
name = "crds_shards"
harness = false

[[bench]]
name = "weighted_shuffle"
harness = false

[lints]
workspace = true
