[package]
name = "trezoa-compute-budget-program"
description = "Trezoa Compute Budget program"
documentation = "https://docs.rs/trezoa-compute-budget-program"
version = { workspace = true }
authors = { workspace = true }
repository = { workspace = true }
homepage = { workspace = true }
license = { workspace = true }
edition = { workspace = true }

[package.metadata.docs.rs]
targets = ["x86_64-unknown-linux-gnu"]

[lib]
crate-type = ["lib"]
name = "trezoa_compute_budget_program"

[features]
trezoa-unstable-api = []

[dependencies]
trezoa-program-runtime = { workspace = true }
