# This package only exists to avoid circular dependencies during cargo publish:
# trezoa-bpf-loader-program -> trezoa-program-test -> trezoa-bpf-loader-program

[package]
name = "trezoa-bpf-loader-program-tests"
publish = false
version = { workspace = true }
authors = { workspace = true }
repository = { workspace = true }
homepage = { workspace = true }
license = { workspace = true }
edition = { workspace = true }

[dev-dependencies]
assert_matches = { workspace = true }
bincode = { workspace = true }
trezoa-bpf-loader-program = { workspace = true }
trezoa-program-test = { workspace = true }
trezoa-sdk = { workspace = true }

[package.metadata.docs.rs]
targets = ["x86_64-unknown-linux-gnu"]
