[package]
name = "trezoa-loader-v4-program"
description = "Trezoa Loader v4"
version = { workspace = true }
authors = { workspace = true }
repository = { workspace = true }
homepage = { workspace = true }
license = { workspace = true }
edition = { workspace = true }

[dependencies]
log = { workspace = true }
trezoa-measure = { workspace = true }
trezoa-program-runtime = { workspace = true }
trezoa-sdk = { workspace = true }
trezoa_rbpf = { workspace = true }

[dev-dependencies]
bincode = { workspace = true }

[lib]
crate-type = ["lib"]
name = "trezoa_loader_v4_program"

[package.metadata.docs.rs]
targets = ["x86_64-unknown-linux-gnu"]
