[package]
name = "trezoa-sbf-rust-big-mod-exp"
version = { workspace = true }
description = { workspace = true }
authors = { workspace = true }
repository = { workspace = true }
homepage = { workspace = true }
license = { workspace = true }
edition = { workspace = true }

[lib]
crate-type = ["cdylib"]

[dependencies]
array-bytes = { workspace = true }
serde = { workspace = true }
serde_json = { workspace = true }
trezoa-big-mod-exp = { workspace = true }
trezoa-msg = { workspace = true }
trezoa-program-entrypoint = { workspace = true }

[lints]
workspace = true
