[package]
name = "trezoa-sbf-rust-param-passing-dep"
description = "Trezoa SBF program written in Rust"
documentation = "https://docs.rs/trezoa-sbf-rust-param-passing-dep"
version = { workspace = true }
authors = { workspace = true }
repository = { workspace = true }
homepage = { workspace = true }
license = { workspace = true }
edition = { workspace = true }

[dependencies]
trezoa-program = { workspace = true }

[package.metadata.docs.rs]
targets = ["x86_64-unknown-linux-gnu"]
