[package]
name = "trezoa-sbf-rust-account-mem-deprecated"
version = { workspace = true }
description = { workspace = true }
authors = { workspace = true }
repository = { workspace = true }
homepage = { workspace = true }
license = { workspace = true }
edition = { workspace = true }

[lib]
crate-type = ["cdylib"]

[dependencies]
trezoa-account-info = { workspace = true }
trezoa-program = { workspace = true }
trezoa-program-error = { workspace = true }
trezoa-program-memory = { workspace = true }
trezoa-pubkey = { workspace = true }

[lints]
workspace = true
