[package]
name = "trezoa-program-binaries"
description = "Prebuilt SPL and Core BPF programs"
version = { workspace = true }
authors = { workspace = true }
repository = { workspace = true }
homepage = { workspace = true }
license = { workspace = true }
edition = { workspace = true }

[features]
trezoa-unstable-api = []

[dependencies]
bincode = { workspace = true }
serde = { workspace = true }
trezoa-account = { workspace = true }
trezoa-loader-v3-interface = { workspace = true, features = ["bincode", "serde"] }
trezoa-pubkey = { workspace = true }
trezoa-rent = { workspace = true }
trezoa-sdk-ids = { workspace = true }
spl-generic-token = { workspace = true }
