[package]
name = "trezoa-udp-client"
description = "Trezoa UDP Client"
documentation = "https://docs.rs/trezoa-udp-client"
version = { workspace = true }
authors = { workspace = true }
repository = { workspace = true }
homepage = { workspace = true }
license = { workspace = true }
edition = { workspace = true }

[dependencies]
async-trait = { workspace = true }
trezoa-connection-cache = { workspace = true }
trezoa-net-utils = { workspace = true }
trezoa-sdk = { workspace = true }
trezoa-streamer = { workspace = true }
thiserror = { workspace = true }
tokio = { workspace = true, features = ["full"] }
