[package]
name = "trezoa-notifier"
description = "Trezoa Notifier"
documentation = "https://docs.rs/trezoa-notifier"
version = { workspace = true }
authors = { workspace = true }
repository = { workspace = true }
homepage = { workspace = true }
license = { workspace = true }
edition = { workspace = true }

[package.metadata.docs.rs]
targets = ["x86_64-unknown-linux-gnu"]

[lib]
name = "trezoa_notifier"

[features]
trezoa-unstable-api = []

[dependencies]
log = { workspace = true }
reqwest = { workspace = true, features = ["blocking", "brotli", "deflate", "gzip", "rustls-tls", "json"] }
serde_json = { workspace = true }
trezoa-hash = { workspace = true }
