[package]
name = "trezoa-unified-scheduler-pool"
description = "The Trezoa unified scheduler pool"
documentation = "https://docs.rs/trezoa-unified-scheduler-pool"
version = { workspace = true }
authors = { workspace = true }
repository = { workspace = true }
homepage = { workspace = true }
license = { workspace = true }
edition = { workspace = true }

[features]
trezoa-unstable-api = []
dev-context-only-utils = []

[dependencies]
trezoa-banking-stage-ingress-types = { workspace = true }
aquamarine = { workspace = true }
assert_matches = { workspace = true }
crossbeam-channel = { workspace = true }
dashmap = { workspace = true }
derive-where = { workspace = true }
derive_more = { workspace = true }
dyn-clone = { workspace = true }
log = { workspace = true }
scopeguard = { workspace = true }
trezoa-clock = { workspace = true }
trezoa-cost-model = { workspace = true }
trezoa-ledger = { workspace = true }
trezoa-metrics = { workspace = true }
trezoa-poh = { workspace = true }
trezoa-pubkey = { workspace = true }
trezoa-runtime = { workspace = true }
trezoa-runtime-transaction = { workspace = true }
trezoa-svm = { workspace = true }
trezoa-svm-timings = { workspace = true }
trezoa-transaction = { workspace = true }
trezoa-transaction-error = { workspace = true }
trezoa-unified-scheduler-logic = { workspace = true }
static_assertions = { workspace = true }
trait-set = { workspace = true }
unwrap_none = { workspace = true }
vec_extract_if_polyfill = { workspace = true }

[dev-dependencies]
trezoa-logger = { workspace = true }
assert_matches = { workspace = true }
trezoa-clock = { workspace = true }
trezoa-entry = { workspace = true }
trezoa-hash = { workspace = true }
trezoa-keypair = { workspace = true }
trezoa-runtime = { workspace = true, features = ["dev-context-only-utils"] }
trezoa-system-transaction = { workspace = true }
# See order-crates-for-publishing.py for using this unusual `path = "."`
trezoa-unified-scheduler-pool = { path = ".", features = ["dev-context-only-utils"] }
test-case = { workspace = true }
