[package]
name = "trezoa-unified-scheduler-pool"
description = "The Trezoa unified scheduler pool"
documentation = "https://docs.rs/trezoa-unified-scheduler-pool"
version = { workspace = true }
authors = { workspace = true }
repository = { workspace = true }
homepage = { workspace = true }
license = { workspace = true }
edition = { workspace = true }

[dependencies]
trezoa-ledger = { workspace = true }
trezoa-program-runtime = { workspace = true }
trezoa-runtime = { workspace = true }
trezoa-sdk = { workspace = true }
trezoa-unified-scheduler-logic = { workspace = true }
trezoa-vote = { workspace = true }

[dev-dependencies]
assert_matches = { workspace = true }
trezoa-logger = { workspace = true }
trezoa-runtime = { workspace = true, features = ["dev-context-only-utils"] }
