[package]
name = "trezoa-votor-messages"
documentation = "https://docs.rs/trezoa-votor-messages"
version = { workspace = true }
authors = { workspace = true }
description = { workspace = true }
repository = { workspace = true }
homepage = { workspace = true }
license = { workspace = true }
edition = { workspace = true }

[features]
trezoa-unstable-api = []
dev-context-only-utils = []
frozen-abi = [
    "dep:trezoa-frozen-abi",
    "dep:trezoa-frozen-abi-macro",
    "trezoa-hash/frozen-abi",
    "trezoa-bls-signatures/frozen-abi",
]

[dependencies]
trezoa-feature-set = { workspace = true }
trezoa-logger = { workspace = true }
log = { workspace = true }
serde = { workspace = true }
trezoa-address = { workspace = true, features = ["curve25519"] }
trezoa-bls-signatures = { workspace = true, features = [
    "bytemuck", "trezoa-signer-derive",
] }
trezoa-clock = { workspace = true }
trezoa-epoch-schedule = { workspace = true }
trezoa-frozen-abi = { workspace = true, optional = true, features = [
    "frozen-abi",
] }
trezoa-frozen-abi-macro = { workspace = true, optional = true, features = [
    "frozen-abi",
] }
trezoa-hash = { workspace = true, features = ["serde"] }
trezoa-pubkey = { workspace = true }

[lints]
workspace = true
