[package]
name = "trezoa-genesis"
description = "Blockchain, Rebuilt for Scale"
documentation = "https://docs.rs/trezoa-genesis"
version = { workspace = true }
authors = { workspace = true }
repository = { workspace = true }
homepage = { workspace = true }
license = { workspace = true }
edition = { workspace = true }

[dependencies]
base64 = { workspace = true }
bincode = { workspace = true }
clap = { workspace = true }
itertools = { workspace = true }
serde = { workspace = true }
serde_json = { workspace = true }
serde_yaml = { workspace = true }
trezoa-accounts-db = { workspace = true }
trezoa-clap-utils = { workspace = true }
trezoa-cli-config = { workspace = true }
trezoa-entry = { workspace = true }
trezoa-ledger = { workspace = true }
trezoa-logger = { workspace = true }
trezoa-runtime = { workspace = true }
trezoa-sdk = { workspace = true }
trezoa-stake-program = { workspace = true }
trezoa-version = { workspace = true }
trezoa-vote-program = { workspace = true }
tempfile = { workspace = true }

[dev-dependencies]
trezoa-runtime = { workspace = true, features = ["dev-context-only-utils"] }

[[bin]]
name = "trezoa-genesis"
path = "src/main.rs"

[lib]
name = "trezoa_genesis"

[package.metadata.docs.rs]
targets = ["x86_64-unknown-linux-gnu"]
