[package]
name = "trezoa-stake-accounts"
description = "Blockchain, Rebuilt for Scale"
documentation = "https://docs.rs/trezoa-stake-accounts"
version = { workspace = true }
authors = { workspace = true }
repository = { workspace = true }
homepage = { workspace = true }
license = { workspace = true }
edition = { workspace = true }

[dependencies]
clap = { workspace = true }
trezoa-clap-utils = { workspace = true }
trezoa-cli-config = { workspace = true }
trezoa-remote-wallet = { workspace = true, features = ["default"] }
trezoa-rpc-client = { workspace = true, features = ["default"] }
trezoa-rpc-client-api = { workspace = true }
trezoa-sdk = { workspace = true }
trezoa-stake-program = { workspace = true }
trezoa-version = { workspace = true }

[dev-dependencies]
trezoa-runtime = { workspace = true, features = ["dev-context-only-utils"] }

[package.metadata.docs.rs]
targets = ["x86_64-unknown-linux-gnu"]
