[package]
name = "trezoa-watchtower"
description = "Blockchain, Rebuilt for Scale"
documentation = "https://docs.rs/trezoa-watchtower"
version = { workspace = true }
authors = { workspace = true }
repository = { workspace = true }
homepage = { workspace = true }
license = { workspace = true }
edition = { workspace = true }

[dependencies]
clap = { workspace = true }
humantime = { workspace = true }
log = { workspace = true }
trezoa-clap-utils = { workspace = true }
trezoa-cli-config = { workspace = true }
trezoa-cli-output = { workspace = true }
trezoa-logger = { workspace = true }
trezoa-metrics = { workspace = true }
trezoa-notifier = { workspace = true }
trezoa-rpc-client = { workspace = true }
trezoa-rpc-client-api = { workspace = true }
trezoa-sdk = { workspace = true }
trezoa-version = { workspace = true }

[package.metadata.docs.rs]
targets = ["x86_64-unknown-linux-gnu"]
