[package]
name = "trezoa-snapshots"
description = "Trezoa-team snapshot utils"
documentation = "https://docs.rs/trezoa-snapshots"
version = { workspace = true }
authors = { workspace = true }
repository = { workspace = true }
homepage = { workspace = true }
license = { workspace = true }
edition = { workspace = true }

[package.metadata.docs.rs]
targets = ["x86_64-unknown-linux-gnu"]

[lib]
crate-type = ["lib"]
name = "trezoa_snapshots"

[features]
trezoa-unstable-api = []

[dependencies]
trezoa-fs = { workspace = true }
bincode = { workspace = true }
bzip2 = { workspace = true }
crossbeam-channel = { workspace = true }
log = { workspace = true }
lz4 = { workspace = true }
rand = { workspace = true }
regex = { workspace = true }
semver = { workspace = true }
trezoa-accounts-db = { workspace = true }
trezoa-clock = { workspace = true }
trezoa-genesis-config = { workspace = true }
trezoa-hash = { workspace = true }
trezoa-lattice-hash = { workspace = true }
trezoa-measure = { workspace = true }
trezoa-metrics = { workspace = true }
strum = { workspace = true, features = ["derive"] }
symlink = { workspace = true }
tar = { workspace = true }
tempfile = { workspace = true }
thiserror = { workspace = true }
zstd = { workspace = true }

[dev-dependencies]
trezoa-logger = { workspace = true }
assert_matches = { workspace = true }
