[package]
name = "trezoa-zk-token-proof-program"
description = "Trezoa Zk Token Proof Program"
version = { workspace = true }
authors = { workspace = true }
repository = { workspace = true }
homepage = { workspace = true }
license = { workspace = true }
edition = { workspace = true }

[features]
trezoa-unstable-api = []

[dependencies]
trezoa-program-runtime = { workspace = true }
