[package]
name = "trezoa-sbf-rust-panic"
documentation = "https://docs.rs/trezoa-sbf-rust-panic"
version = { workspace = true }
description = { workspace = true }
authors = { workspace = true }
repository = { workspace = true }
homepage = { workspace = true }
license = { workspace = true }
edition = { workspace = true }

[dependencies]
trezoa-program = { workspace = true }

[features]
default = ["custom-panic"]
custom-panic = []

[lib]
crate-type = ["cdylib"]

[package.metadata.docs.rs]
targets = ["x86_64-unknown-linux-gnu"]
