[package]
name = "trezoa-transaction-metrics-tracker"
description = "Trezoa transaction metrics tracker"
documentation = "https://docs.rs/trezoa-transaction-metrics-tracker"
version = { workspace = true }
authors = { workspace = true }
repository = { workspace = true }
homepage = { workspace = true }
license = { workspace = true }
edition = { workspace = true }

[package.metadata.docs.rs]
targets = ["x86_64-unknown-linux-gnu"]

[features]
trezoa-unstable-api = []

[dependencies]
base64 = { workspace = true }
bincode = { workspace = true }
# Update this borsh dependency to the workspace version once
log = { workspace = true }
rand = { workspace = true }
trezoa-packet = { workspace = true }
trezoa-perf = { workspace = true }
trezoa-short-vec = { workspace = true }
trezoa-signature = { workspace = true }

[dev-dependencies]
trezoa-hash = { workspace = true }
trezoa-keypair = { workspace = true }
trezoa-packet = { workspace = true, features = ["dev-context-only-utils"] }
trezoa-perf = { workspace = true, features = ["dev-context-only-utils"] }
trezoa-pubkey = { workspace = true, features = ["rand"] }
trezoa-system-transaction = { workspace = true }
