[package]
name = "trezoa-fs"
description = "Trezoa-team file system utils"
documentation = "https://docs.rs/trezoa-fs"
version = { workspace = true }
authors = { workspace = true }
repository = { workspace = true }
homepage = { workspace = true }
license = { workspace = true }
edition = { workspace = true }

[package.metadata.docs.rs]
targets = ["x86_64-unknown-linux-gnu"]

[lib]
crate-type = ["lib"]
name = "trezoa_fs"

[features]
trezoa-unstable-api = []

[dependencies]
libc = { workspace = true }
log = { workspace = true }
slab = { workspace = true }
smallvec = { workspace = true }
thiserror = { workspace = true }

[target.'cfg(target_os = "linux")'.dependencies]
trezoa-io-uring = { workspace = true }
io-uring = { workspace = true }

[dev-dependencies]
rand = { workspace = true }
tempfile = { workspace = true }
test-case = { workspace = true }
