[package]
name = "trezoa-genesis-utils"
description = "Trezoa Genesis Utils"
documentation = "https://docs.rs/trezoa-download-utils"
version = { workspace = true }
authors = { workspace = true }
repository = { workspace = true }
homepage = { workspace = true }
license = { workspace = true }
edition = { workspace = true }

[dependencies]
log = { workspace = true }
trezoa-accounts-db = { workspace = true }
trezoa-download-utils = { workspace = true }
trezoa-rpc-client = { workspace = true }
trezoa-sdk = { workspace = true }

[lib]
crate-type = ["lib"]
name = "trezoa_genesis_utils"

[package.metadata.docs.rs]
targets = ["x86_64-unknown-linux-gnu"]
