[package]
name = "trezoa-genesis-utils"
description = "Trezoa Genesis Utils"
documentation = "https://docs.rs/trezoa-download-utils"
version = { workspace = true }
authors = { workspace = true }
repository = { workspace = true }
homepage = { workspace = true }
license = { workspace = true }
edition = { workspace = true }

[package.metadata.docs.rs]
targets = ["x86_64-unknown-linux-gnu"]

[lib]
crate-type = ["lib"]
name = "trezoa_genesis_utils"

[features]
trezoa-unstable-api = []

[dependencies]
trezoa-snapshots = { workspace = true }
log = { workspace = true }
trezoa-download-utils = { workspace = true }
trezoa-genesis-config = { workspace = true }
trezoa-hash = { workspace = true }
trezoa-rpc-client = { workspace = true }
thiserror = { workspace = true }
