[package]
name = "trezoa-quic-client"
description = "Trezoa Quic Client"
documentation = "https://docs.rs/trezoa-quic-client"
version = { workspace = true }
authors = { workspace = true }
repository = { workspace = true }
homepage = { workspace = true }
license = { workspace = true }
edition = { workspace = true }

[dependencies]
async-mutex = { workspace = true }
async-trait = { workspace = true }
futures = { workspace = true }
itertools = { workspace = true }
lazy_static = { workspace = true }
log = { workspace = true }
quinn = { workspace = true }
quinn-proto = { workspace = true }
rcgen = { workspace = true }
rustls = { workspace = true, features = ["dangerous_configuration"] }
trezoa-connection-cache = { workspace = true }
trezoa-measure = { workspace = true }
trezoa-metrics = { workspace = true }
trezoa-net-utils = { workspace = true }
trezoa-rpc-client-api = { workspace = true }
trezoa-sdk = { workspace = true }
trezoa-streamer = { workspace = true }
thiserror = { workspace = true }
tokio = { workspace = true, features = ["full"] }

[dev-dependencies]
crossbeam-channel = { workspace = true }
trezoa-logger = { workspace = true }
trezoa-perf = { workspace = true }
