[package]
name = "trezoa-perf"
description = "Trezoa Performance APIs"
documentation = "https://docs.rs/trezoa-perf"
version = { workspace = true }
authors = { workspace = true }
repository = { workspace = true }
homepage = { workspace = true }
license = { workspace = true }
edition = { workspace = true }

[package.metadata.docs.rs]
targets = ["x86_64-unknown-linux-gnu"]

[lib]
name = "trezoa_perf"

[features]
trezoa-unstable-api = []
dev-context-only-utils = [
    "dep:trezoa-clock",
    "dep:trezoa-keypair",
    "dep:trezoa-signer",
    "dep:trezoa-system-interface",
    "dep:trezoa-system-transaction",
    "dep:trezoa-transaction",
    "dep:trezoa-vote-program",
    "dep:trezoa-vote",
]
frozen-abi = [
    "dep:trezoa-frozen-abi",
    "dep:trezoa-frozen-abi-macro",
    "trezoa-short-vec/frozen-abi",
    "trezoa-vote-program/frozen-abi",
]

[dependencies]
ahash = { workspace = true }
bincode = { workspace = true }
bv = { workspace = true, features = ["serde"] }
bytes = { workspace = true, features = ["serde"] }
curve25519-dalek = { workspace = true }
dlopen2 = { workspace = true }
fnv = { workspace = true }
log = { workspace = true }
rand = { workspace = true }
rayon = { workspace = true }
serde = { workspace = true }
trezoa-clock = { workspace = true, optional = true }
trezoa-frozen-abi = { workspace = true, optional = true, features = [
    "frozen-abi",
] }
trezoa-frozen-abi-macro = { workspace = true, optional = true, features = [
    "frozen-abi",
] }
trezoa-hash = { workspace = true }
trezoa-keypair = { workspace = true, optional = true }
trezoa-message = { workspace = true }
trezoa-metrics = { workspace = true }
trezoa-packet = { workspace = true, features = ["bincode"] }
trezoa-pubkey = { workspace = true, default-features = false }
trezoa-rayon-threadlimit = { workspace = true }
trezoa-sdk-ids = { workspace = true }
trezoa-short-vec = { workspace = true }
trezoa-signature = { workspace = true, features = ["verify"] }
trezoa-signer = { workspace = true, optional = true }
trezoa-system-interface = { workspace = true, optional = true }
trezoa-system-transaction = { workspace = true, optional = true }
trezoa-time-utils = { workspace = true }
trezoa-transaction = { workspace = true, optional = true }
trezoa-transaction-context = { workspace = true }
trezoa-vote = { workspace = true, optional = true }
trezoa-vote-program = { workspace = true, optional = true }

[target."cfg(target_os = \"linux\")".dependencies]
caps = { workspace = true }
libc = { workspace = true }
nix = { workspace = true, features = ["user"] }

[dev-dependencies]
trezoa-logger = { workspace = true }
trezoa-random = { workspace = true }
assert_matches = { workspace = true }
bencher = { workspace = true }
rand_chacha = { workspace = true }
trezoa-perf = { path = ".", features = ["trezoa-unstable-api", "dev-context-only-utils"] }
test-case = { workspace = true }

[target.'cfg(not(any(target_env = "msvc", target_os = "freebsd")))'.dev-dependencies]
jemallocator = { workspace = true }

[[bench]]
name = "dedup"
harness = false

[[bench]]
name = "recycler"
harness = false

[[bench]]
name = "reset"
harness = false

[[bench]]
name = "shrink"
harness = false

[[bench]]
name = "sigverify"
harness = false

[[bench]]
name = "discard"
harness = false

[lints.rust.unexpected_cfgs]
level = "warn"
check-cfg = ['cfg(build_target_feature_avx)', 'cfg(build_target_feature_avx2)']
