[package]
name = "trezoa-tpu-client-next"
description = "Client code to send transaction to TPU."
version = { workspace = true }
authors = { workspace = true }
repository = { workspace = true }
homepage = { workspace = true }
license = { workspace = true }
edition = { workspace = true }

[package.metadata.docs.rs]
targets = ["x86_64-unknown-linux-gnu"]

[features]
trezoa-unstable-api = []
dev-context-only-utils = []
metrics = ["dep:trezoa-metrics"]
tracing = ["dep:tracing"]
websocket-node-address-service = ["dep:trezoa-pubsub-client", "dep:tokio-stream"]

[dependencies]
async-trait = { workspace = true }
futures = { workspace = true }
futures-util = { workspace = true }
log = { workspace = true }
lru = { workspace = true }
quinn = { workspace = true }
rustls = { workspace = true }
trezoa-clock = { workspace = true }
trezoa-commitment-config = { workspace = true }
trezoa-epoch-schedule = { workspace = true }
trezoa-keypair = { workspace = true }
trezoa-measure = { workspace = true }
trezoa-metrics = { workspace = true, optional = true }
trezoa-pubkey = { workspace = true }
trezoa-pubsub-client = { workspace = true, optional = true }
trezoa-quic-definitions = { workspace = true }
trezoa-rpc-client = { workspace = true }
trezoa-rpc-client-api = { workspace = true }
trezoa-streamer = { workspace = true }
trezoa-time-utils = { workspace = true }
trezoa-tls-utils = { workspace = true }
thiserror = { workspace = true }
tokio = { workspace = true }
tokio-stream = { workspace = true, optional = true }
tokio-util = { workspace = true }
tracing = { workspace = true, optional = true }

[dev-dependencies]
crossbeam-channel = { workspace = true }
futures = { workspace = true }
serde_json = { workspace = true }
trezoa-cli-config = { workspace = true }
trezoa-commitment-config = { workspace = true }
trezoa-net-utils = { workspace = true }
trezoa-pubkey = { workspace = true }
trezoa-signer = { workspace = true }
trezoa-streamer = { workspace = true, features = ["dev-context-only-utils"] }
trezoa-tpu-client-next = { path = ".", features = ["trezoa-unstable-api", "websocket-node-address-service", "dev-context-only-utils"] }
