[package]
name = "trezoa-poh-bench"
documentation = "https://docs.rs/trezoa-poh-bench"
publish = false
version = { workspace = true }
authors = { workspace = true }
repository = { workspace = true }
homepage = { workspace = true }
license = { workspace = true }
edition = { workspace = true }

[dependencies]
clap = { version = "3.1.5", features = ["cargo"] }
log = { workspace = true }
rayon = { workspace = true }
trezoa-entry = { workspace = true }
trezoa-logger = { workspace = true }
trezoa-measure = { workspace = true }
trezoa-perf = { workspace = true }
trezoa-sdk = { workspace = true }
trezoa-version = { workspace = true }

[package.metadata.docs.rs]
targets = ["x86_64-unknown-linux-gnu"]
