[package]
name = "trezoa-logger"
description = "Trezoa Logger"
documentation = "https://docs.rs/trezoa-logger"
version = { workspace = true }
authors = { workspace = true }
repository = { workspace = true }
homepage = { workspace = true }
license = { workspace = true }
edition = { workspace = true }

[dependencies]
env_logger = { workspace = true }
lazy_static = { workspace = true }
log = { workspace = true }

[lib]
name = "trezoa_logger"

[package.metadata.docs.rs]
targets = ["x86_64-unknown-linux-gnu"]
