[package]
name = "trezoa-geyser-plugin-interface"
description = "The Trezoa Geyser plugin interface."
documentation = "https://docs.rs/trezoa-geyser-plugin-interface"
version = { workspace = true }
authors = { workspace = true }
repository = { workspace = true }
homepage = { workspace = true }
license = { workspace = true }
edition = { workspace = true }

[package.metadata.docs.rs]
targets = ["x86_64-unknown-linux-gnu"]

[features]
trezoa-unstable-api = []

[dependencies]
log = { workspace = true, features = ["std"] }
trezoa-clock = { workspace = true }
trezoa-hash = { workspace = true }
trezoa-signature = { workspace = true }
trezoa-transaction = { workspace = true }
trezoa-transaction-status = { workspace = true }
thiserror = { workspace = true }
