[package]
name = "trezoa-geyser-plugin-interface"
description = "The Trezoa Geyser plugin interface."
documentation = "https://docs.rs/trezoa-geyser-plugin-interface"
version = { workspace = true }
authors = { workspace = true }
repository = { workspace = true }
homepage = { workspace = true }
license = { workspace = true }
edition = { workspace = true }

[dependencies]
log = { workspace = true }
trezoa-sdk = { workspace = true }
trezoa-transaction-status = { workspace = true }
thiserror = { workspace = true }

[package.metadata.docs.rs]
targets = ["x86_64-unknown-linux-gnu"]
