[package]
name = "trezoa-transaction-context"
description = "Trezoa data shared between program runtime and built-in programs as well as SBF programs."
documentation = "https://docs.rs/trezoa-transaction-context"
version = { workspace = true }
authors = { workspace = true }
repository = { workspace = true }
homepage = { workspace = true }
license = { workspace = true }
edition = { workspace = true }

[package.metadata.docs.rs]
targets = ["x86_64-unknown-linux-gnu"]
all-features = true
rustdoc-args = ["--cfg=docsrs"]

[features]
trezoa-unstable-api = []
bincode = ["dep:bincode", "serde", "trezoa-account/bincode"]
dev-context-only-utils = ["bincode", "trezoa-account/dev-context-only-utils", "dep:qualifier_attr"]
serde = ["serde/derive", "trezoa-pubkey/serde"]

[dependencies]
qualifier_attr = { workspace = true, optional = true }
serde = { workspace = true, optional = true }
trezoa-account = { workspace = true }
trezoa-instruction = { workspace = true, features = ["std"] }
trezoa-instructions-sysvar = { workspace = true }
trezoa-pubkey = { workspace = true }
trezoa-sbpf = { workspace = true }

[target.'cfg(not(target_os = "trezoa"))'.dependencies]
bincode = { workspace = true, optional = true }
trezoa-rent = { workspace = true }
trezoa-sdk-ids = { workspace = true }
trezoa-signature = { workspace = true, optional = true }

[dev-dependencies]
trezoa-account-info = { workspace = true }
trezoa-program-entrypoint = { workspace = true }
trezoa-system-interface = { workspace = true }
trezoa-transaction-context = { path = ".", features = [
    "trezoa-unstable-api",
    "dev-context-only-utils",
] }
static_assertions = { workspace = true }

[lints]
workspace = true
