[package]
name = "trezoa-svm-callback"
description = "Trezoa SVM callback"
version = { workspace = true }
authors = { workspace = true }
repository = { workspace = true }
homepage = { workspace = true }
license = { workspace = true }
edition = { workspace = true }
readme = false

[features]
trezoa-unstable-api = []

[dependencies]
trezoa-account = { workspace = true }
trezoa-clock = { workspace = true }
trezoa-precompile-error = { workspace = true }
trezoa-pubkey = { workspace = true }

[lints]
workspace = true
