[package]
name = "trezoa-sbf-rust-alt-bn128"
description = "Trezoa BPF test program written in Rust"
version = { workspace = true }
authors = { workspace = true }
repository = { workspace = true }
homepage = { workspace = true }
license = { workspace = true }
edition = { workspace = true }

[lib]
crate-type = ["cdylib"]

[dependencies]
array-bytes = { workspace = true }
trezoa-bn254 = { workspace = true }
trezoa-msg = { workspace = true }
trezoa-program-entrypoint = { workspace = true }

[lints]
workspace = true
