[package]
name = "trezoa-scheduling-utils"
description = "Common utilities for building Trezoa-team scheduler implementations"
documentation = "https://docs.rs/trezoa-scheduling-utils"
version = { workspace = true }
authors = { workspace = true }
repository = { workspace = true }
homepage = { workspace = true }
license = { workspace = true }
edition = { workspace = true }

[features]
trezoa-unstable-api = []
dev-context-only-utils = []

[dependencies]
trezoa-scheduler-bindings = { workspace = true }
ahash = { workspace = true }
trezoa-pubkey = { workspace = true }
trezoa-transaction-error = { workspace = true }

[target."cfg(unix)".dependencies]
trezoa-transaction-view = { workspace = true }
libc = { workspace = true }
nix = { workspace = true, features = ["socket", "uio"] }
rts-alloc = { workspace = true }
shaq = { workspace = true }
thiserror = { workspace = true }

[dev-dependencies]
tempfile = { workspace = true }

[target."cfg(unix)".dev-dependencies]
trezoa-scheduler-bindings = { workspace = true, features = ["dev-context-only-utils"] }

[lints]
workspace = true
