[package]
name = "trezoa-runtime-transaction"
description = "Trezoa runtime-transaction"
documentation = "https://docs.rs/trezoa-runtime-transaction"
version = { workspace = true }
authors = { workspace = true }
repository = { workspace = true }
homepage = { workspace = true }
license = { workspace = true }
edition = { workspace = true }

[dependencies]
log = { workspace = true }
trezoa-program-runtime = { workspace = true }
trezoa-sdk = { workspace = true }
thiserror = { workspace = true }

[lib]
crate-type = ["lib"]
name = "trezoa_runtime_transaction"

[dev-dependencies]
bincode = { workspace = true }
rand = { workspace = true }
trezoa-program ={ workspace = true }

[package.metadata.docs.rs]
targets = ["x86_64-unknown-linux-gnu"]

[build-dependencies]
rustc_version = { workspace = true }
