[package]
name = "trezoa-store-histogram"
description = "Tool to calculate account storage histogram"
publish = false
version = { workspace = true }
authors = { workspace = true }
repository = { workspace = true }
homepage = { workspace = true }
license = { workspace = true }
edition = { workspace = true }

[features]
trezoa-unstable-api = []
dev-context-only-utils = []

[dependencies]
clap = { workspace = true }
trezoa-version = { workspace = true }
