[package]
name = "trezoa-frozen-abi"
description = "Trezoa Frozen ABI"
documentation = "https://docs.rs/trezoa-frozen-abi"
version = { workspace = true }
authors = { workspace = true }
repository = { workspace = true }
homepage = { workspace = true }
license = { workspace = true }
edition = { workspace = true }

[dependencies]
bs58 = { workspace = true }
bv = { workspace = true, features = ["serde"] }
lazy_static = { workspace = true }
log = { workspace = true, features = ["std"] }
serde = { workspace = true, features = ["derive", "rc"] }
serde_bytes = { workspace = true }
serde_derive = { workspace = true }
sha2 = { workspace = true }
trezoa-frozen-abi-macro = { workspace = true }
thiserror = { workspace = true }

[target.'cfg(not(target_os = "trezoa"))'.dependencies]
block-buffer = { workspace = true }
either = { workspace = true, features = ["use_std"] }
generic-array = { workspace = true, features = ["serde", "more_lengths"] }
im = { workspace = true, features = ["rayon", "serde"] }
memmap2 = { workspace = true }
subtle = { workspace = true }

[target.'cfg(not(target_os = "trezoa"))'.dev-dependencies]
bitflags = { workspace = true }
trezoa-logger = { workspace = true }

[build-dependencies]
rustc_version = { workspace = true }
