[package]
name = "trezoa-download-utils"
description = "Trezoa Download Utils"
documentation = "https://docs.rs/trezoa-download-utils"
version = { workspace = true }
authors = { workspace = true }
repository = { workspace = true }
homepage = { workspace = true }
license = { workspace = true }
edition = { workspace = true }

[dependencies]
console = { workspace = true }
indicatif = { workspace = true }
log = { workspace = true }
reqwest = { workspace = true, features = ["blocking", "brotli", "deflate", "gzip", "rustls-tls", "json"] }
trezoa-runtime = { workspace = true }
trezoa-sdk = { workspace = true }

[dev-dependencies]
trezoa-runtime = { workspace = true, features = ["dev-context-only-utils"] }

[lib]
crate-type = ["lib"]
name = "trezoa_download_utils"

[package.metadata.docs.rs]
targets = ["x86_64-unknown-linux-gnu"]
