[package]
name = "trezoa-cost-model"
description = "Trezoa cost model"
documentation = "https://docs.rs/trezoa-cost-model"
version = { workspace = true }
authors = { workspace = true }
repository = { workspace = true }
homepage = { workspace = true }
license = { workspace = true }
edition = { workspace = true }

[dependencies]
lazy_static = { workspace = true }
log = { workspace = true }
trezoa-address-lookup-table-program = { workspace = true }
trezoa-bpf-loader-program = { workspace = true }
trezoa-compute-budget-program = { workspace = true }
trezoa-config-program = { workspace = true }
trezoa-frozen-abi = { workspace = true }
trezoa-frozen-abi-macro = { workspace = true }
trezoa-loader-v4-program = { workspace = true }
trezoa-metrics = { workspace = true }
trezoa-program-runtime = { workspace = true }
trezoa-sdk = { workspace = true }
trezoa-stake-program = { workspace = true }
trezoa-system-program = { workspace = true }
trezoa-vote-program = { workspace = true }

[lib]
crate-type = ["lib"]
name = "trezoa_cost_model"

[dev-dependencies]
trezoa-logger = { workspace = true }
trezoa-sdk = { workspace = true, features = ["dev-context-only-utils"] }
static_assertions = { workspace = true }
test-case = { workspace = true }

[package.metadata.docs.rs]
targets = ["x86_64-unknown-linux-gnu"]

[build-dependencies]
rustc_version = { workspace = true }
