[package]
name = "trezoa-gossip-bin"
version = { workspace = true }
authors = { workspace = true }
description = "Binary crate providing the Trezoa Gossip command-line tool."
repository = { workspace = true }
homepage = { workspace = true }
license = { workspace = true }
publish = false
edition = { workspace = true }

[[bin]]
name = "trezoa-gossip"
path = "src/main.rs"
bench = false

[features]
trezoa-unstable-api = []

[dependencies]
trezoa-logger = { workspace = true }
clap = { workspace = true }
log = { workspace = true }
trezoa-clap-utils = { workspace = true }
trezoa-gossip = { workspace = true, features = ["trezoa-unstable-api"] }
trezoa-net-utils = { workspace = true, features = ["trezoa-unstable-api"] }
trezoa-pubkey = { version = "=4.0.0", features = ["rand"] }
trezoa-version = { workspace = true }
