[package]
name = "trezoa-ledger-tool"
documentation = "https://docs.rs/trezoa-ledger-tool"
version = { workspace = true }
authors = { workspace = true }
description = { workspace = true }
repository = { workspace = true }
homepage = { workspace = true }
license = { workspace = true }
edition = { workspace = true }
workspace = "../dev-bins"

[package.metadata.docs.rs]
targets = ["x86_64-unknown-linux-gnu"]

[features]
trezoa-unstable-api = []
dev-context-only-utils = []
dummy-for-ci-check = []
frozen-abi = []

[dependencies]
trezoa-feature-set = { workspace = true }
trezoa-logger = { workspace = true }
trezoa-reserved-account-keys = { workspace = true }
trezoa-snapshots = { workspace = true }
trezoa-syscalls = { workspace = true }
bs58 = { workspace = true }
chrono = { workspace = true, features = ["default"] }
clap = { workspace = true }
crossbeam-channel = { workspace = true }
csv = { workspace = true }
dashmap = { workspace = true }
futures = { workspace = true }
histogram = { workspace = true }
itertools = { workspace = true }
log = { workspace = true }
num_cpus = { workspace = true }
pretty-hex = { workspace = true }
rayon = { workspace = true }
regex = { workspace = true }
serde = { workspace = true }
serde_bytes = { workspace = true }
serde_json = { workspace = true }
trezoa-account  = { workspace = true }
trezoa-account-decoder = { workspace = true }
trezoa-accounts-db = { workspace = true }
trezoa-bpf-loader-program = { workspace = true }
trezoa-clap-utils = { workspace = true }
trezoa-cli-output = { workspace = true }
trezoa-clock = { workspace = true }
trezoa-cluster-type = { workspace = true }
trezoa-compute-budget = { workspace = true }
trezoa-core = { workspace = true, features = ["dev-context-only-utils"] }
trezoa-cost-model = { workspace = true }
trezoa-entry = { workspace = true }
trezoa-feature-gate-interface = { workspace = true }
trezoa-genesis-config = { workspace = true }
trezoa-genesis-utils = { workspace = true }
trezoa-geyser-plugin-manager = { workspace = true }
trezoa-gossip = { workspace = true }
trezoa-hash = { workspace = true }
trezoa-inflation = { workspace = true }
trezoa-instruction = { workspace = true }
trezoa-keypair = { workspace = true }
trezoa-ledger = { workspace = true, features = ["dev-context-only-utils", "trezoa-unstable-api"] }
trezoa-loader-v3-interface = { workspace = true }
trezoa-measure = { workspace = true }
trezoa-message = { workspace = true }
trezoa-native-token = { workspace = true }
trezoa-program-runtime = { workspace = true, features = ["metrics"] }
trezoa-pubkey = { workspace = true }
trezoa-rent = { workspace = true }
trezoa-rpc = { workspace = true, features = ["dev-context-only-utils"] }
trezoa-runtime = { workspace = true, features = ["dev-context-only-utils"] }
trezoa-runtime-transaction = { workspace = true }
trezoa-sbpf = { workspace = true, features = ["debugger", "jit"] }
trezoa-sdk-ids = { workspace = true }
trezoa-shred-version = { workspace = true }
trezoa-signature = { workspace = true }
trezoa-stake-interface = { workspace = true }
trezoa-storage-bigtable = { workspace = true }
trezoa-svm-callback = { workspace = true }
trezoa-svm-feature-set = { workspace = true }
trezoa-svm-log-collector = { workspace = true }
trezoa-svm-type-overrides = { workspace = true }
trezoa-system-interface = { workspace = true }
trezoa-transaction = { workspace = true }
trezoa-transaction-context = { workspace = true }
trezoa-transaction-status = { workspace = true }
trezoa-unified-scheduler-pool = { workspace = true, features = ["dev-context-only-utils"] }
trezoa-version = { workspace = true }
trezoa-vote = { workspace = true }
trezoa-vote-program = { workspace = true }
thiserror = { workspace = true }
tokio = { workspace = true, features = ["full"] }

[target.'cfg(not(any(target_env = "msvc", target_os = "freebsd")))'.dependencies]
jemallocator = { workspace = true }

[target."cfg(unix)".dependencies]
signal-hook = { workspace = true }

[dev-dependencies]
assert_cmd = { workspace = true }
