[package]
name = "trezoa-ledger-tool"
description = "Blockchain, Rebuilt for Scale"
documentation = "https://docs.rs/trezoa-ledger-tool"
version = { workspace = true }
authors = { workspace = true }
repository = { workspace = true }
homepage = { workspace = true }
license = { workspace = true }
edition = { workspace = true }

[dependencies]
bs58 = { workspace = true }
chrono = { workspace = true, features = ["default"] }
clap = { workspace = true }
crossbeam-channel = { workspace = true }
csv = { workspace = true }
dashmap = { workspace = true }
futures = { workspace = true }
histogram = { workspace = true }
itertools = { workspace = true }
log = { workspace = true }
num_cpus = { workspace = true }
regex = { workspace = true }
serde = { workspace = true, features = ["derive"] }
serde_json = { workspace = true }
trezoa-account-decoder = { workspace = true }
trezoa-accounts-db = { workspace = true }
trezoa-bpf-loader-program = { workspace = true }
trezoa-clap-utils = { workspace = true }
trezoa-cli-output = { workspace = true }
trezoa-core = { workspace = true }
trezoa-cost-model = { workspace = true }
trezoa-entry = { workspace = true }
trezoa-geyser-plugin-manager = { workspace = true }
trezoa-gossip = { workspace = true }
trezoa-ledger = { workspace = true }
trezoa-logger = { workspace = true }
trezoa-measure = { workspace = true }
trezoa-program-runtime = { workspace = true }
trezoa-rpc = { workspace = true }
trezoa-runtime = { workspace = true, features = ["dev-context-only-utils"] }
trezoa-sdk = { workspace = true }
trezoa-stake-program = { workspace = true }
trezoa-storage-bigtable = { workspace = true }
trezoa-streamer = { workspace = true }
trezoa-transaction-status = { workspace = true }
trezoa-unified-scheduler-pool = { workspace = true }
trezoa-version = { workspace = true }
trezoa-vote-program = { workspace = true }
trezoa_rbpf = { workspace = true, features = ["debugger"] }
thiserror = { workspace = true }
tokio = { workspace = true, features = ["full"] }

[target.'cfg(not(target_env = "msvc"))'.dependencies]
jemallocator = { workspace = true }

[dev-dependencies]
assert_cmd = { workspace = true }
bytecount = { workspace = true }

[features]
dev-context-only-utils = []

[target."cfg(unix)".dependencies]
signal-hook = { workspace = true }

[package.metadata.docs.rs]
targets = ["x86_64-unknown-linux-gnu"]
