[package]
name = "trezoa-storage-bigtable"
description = "Trezoa Storage BigTable"
documentation = "https://docs.rs/trezoa-storage-bigtable"
version = { workspace = true }
authors = { workspace = true }
repository = { workspace = true }
homepage = { workspace = true }
license = { workspace = true }
edition = { workspace = true }

[package.metadata.docs.rs]
targets = ["x86_64-unknown-linux-gnu"]

[lib]
crate-type = ["lib"]
name = "trezoa_storage_bigtable"

[features]
trezoa-unstable-api = []

[dependencies]
trezoa-reserved-account-keys = { workspace = true }
backoff = { workspace = true, features = ["tokio"] }
bincode = { workspace = true }
bytes = { workspace = true }
bzip2 = { workspace = true }
enum-iterator = { workspace = true }
flate2 = { workspace = true }
futures = { workspace = true }
goauth = { workspace = true }
http = { workspace = true }
hyper = { workspace = true }
hyper-proxy = { workspace = true }
log = { workspace = true }
# openssl is a dependency of the goauth and smpl_jwt crates, but explicitly
# declare it here as well to activate the "vendored" feature that builds OpenSSL
openssl = { workspace = true, features = ["vendored"] }
prost = { workspace = true }
prost-types = { workspace = true }
serde = { workspace = true }
smpl_jwt = { workspace = true }
trezoa-clock = { workspace = true }
trezoa-message = { workspace = true }
trezoa-metrics = { workspace = true }
trezoa-pubkey = { workspace = true }
trezoa-serde = { workspace = true }
trezoa-signature = { workspace = true }
trezoa-storage-proto = { workspace = true }
trezoa-time-utils = { workspace = true }
trezoa-transaction = { workspace = true }
trezoa-transaction-error = { workspace = true }
trezoa-transaction-status = { workspace = true }
thiserror = { workspace = true }
tokio = { workspace = true }
tonic = { workspace = true, features = ["tls", "transport"] }
zstd = { workspace = true }

[dev-dependencies]
trezoa-hash = { workspace = true }
trezoa-keypair = { workspace = true }
trezoa-pubkey = { workspace = true, features = ["rand"] }
trezoa-system-transaction = { workspace = true }
trezoa-transaction-context = { workspace = true }
