[package]
name = "trezoa-scheduler-bindings"
description = "Trezoa-team scheduler-binding message types for external pack process integration"
documentation = "https://docs.rs/trezoa-scheduler-bindings"
version = { workspace = true }
authors = { workspace = true }
repository = { workspace = true }
homepage = { workspace = true }
license = { workspace = true }
edition = { workspace = true }

[features]
trezoa-unstable-api = []
dev-context-only-utils = []

[dependencies]

[lints]
workspace = true
