[package]
name = "trezoa-zk-elgamal-proof-program"
description = "Trezoa Zk ElGamal Proof Program"
version = { workspace = true }
authors = { workspace = true }
repository = { workspace = true }
homepage = { workspace = true }
license = { workspace = true }
edition = { workspace = true }

[features]
trezoa-unstable-api = []

[dependencies]
trezoa-feature-set = { workspace = true }
bytemuck = { workspace = true }
num-derive = { workspace = true }
num-traits = { workspace = true }
trezoa-instruction = { workspace = true, features = ["std"] }
trezoa-program-runtime = { workspace = true }
trezoa-sdk-ids = { workspace = true }
trezoa-svm-log-collector = { workspace = true }
trezoa-zk-sdk = { workspace = true }

[dev-dependencies]
criterion = { workspace = true }
curve25519-dalek = { workspace = true }

[[bench]]
name = "verify_proofs"
harness = false
