[package]
description = "Trezoa Program Test Framework"
name = "trezoa-program-test"
version = { workspace = true }
authors = { workspace = true }
repository = { workspace = true }
homepage = { workspace = true }
license = { workspace = true }
edition = { workspace = true }

[dependencies]
assert_matches = { workspace = true }
async-trait = { workspace = true }
base64 = { workspace = true }
bincode = { workspace = true }
chrono-humanize = { workspace = true }
crossbeam-channel = { workspace = true }
log = { workspace = true }
serde = { workspace = true }
trezoa-accounts-db = { workspace = true }
trezoa-banks-client = { workspace = true }
trezoa-banks-interface = { workspace = true }
trezoa-banks-server = { workspace = true }
trezoa-bpf-loader-program = { workspace = true }
trezoa-logger = { workspace = true }
trezoa-program-runtime = { workspace = true }
trezoa-runtime = { workspace = true }
trezoa-sdk = { workspace = true }
trezoa-vote-program = { workspace = true }
trezoa_rbpf = { workspace = true }
test-case = { workspace = true }
thiserror = { workspace = true }
tokio = { workspace = true, features = ["full"] }

[dev-dependencies]
trezoa-stake-program = { workspace = true }
