[package]
name = "trezoa-sbf-rust-param-passing"
documentation = "https://docs.rs/trezoa-sbf-rust-param-passing"
version = { workspace = true }
description = { workspace = true }
authors = { workspace = true }
repository = { workspace = true }
homepage = { workspace = true }
license = { workspace = true }
edition = { workspace = true }

[dependencies]
trezoa-program = { workspace = true }
trezoa-sbf-rust-param-passing-dep = { workspace = true }

[lib]
crate-type = ["cdylib"]

[package.metadata.docs.rs]
targets = ["x86_64-unknown-linux-gnu"]
