[package]
name = "trezoa-rpc-client-nonce-utils"
description = "Trezoa RPC Client Nonce Utilities"
documentation = "https://docs.rs/trezoa-nonce-client"
version = { workspace = true }
authors = { workspace = true }
repository = { workspace = true }
homepage = { workspace = true }
license = { workspace = true }
edition = { workspace = true }

[dependencies]
clap = "2.33.0"
trezoa-clap-utils = { workspace = true }
trezoa-rpc-client = { workspace = true }
trezoa-sdk = { workspace = true }
thiserror = { workspace = true }

[dev-dependencies]
anyhow = { workspace = true }
futures = { workspace = true }
serde_json = { workspace = true }
trezoa-account-decoder = { workspace = true }
trezoa-rpc-client-api = { workspace = true }
tokio = { workspace = true, features = ["full"] }

[package.metadata.docs.rs]
targets = ["x86_64-unknown-linux-gnu"]
