[package]
name = "trezoa-sbf-rust-sha"
version = { workspace = true }
description = { workspace = true }
authors = { workspace = true }
repository = { workspace = true }
homepage = { workspace = true }
license = { workspace = true }
edition = { workspace = true }

[lib]
crate-type = ["cdylib"]

[dependencies]
blake3 = { workspace = true }
sha2 = { workspace = true }
sha3 = { workspace = true }
trezoa-blake3-hasher = { workspace = true, features = ["blake3"] }
trezoa-hash = { workspace = true }
trezoa-keccak-hasher = { workspace = true, features = ["sha3"] }
trezoa-msg = { workspace = true }
trezoa-program-entrypoint = { workspace = true }
trezoa-sha256-hasher = { workspace = true, features = ["sha2"] }

[lints]
workspace = true
