[package]
name = "trezoa-send-transaction-service"
description = "Trezoa send transaction service"
documentation = "https://docs.rs/trezoa-send-transaction-service"
version = { workspace = true }
authors = { workspace = true }
repository = { workspace = true }
homepage = { workspace = true }
license = { workspace = true }
edition = { workspace = true }

[dependencies]
crossbeam-channel = { workspace = true }
log = { workspace = true }
trezoa-client = { workspace = true }
trezoa-measure = { workspace = true }
trezoa-metrics = { workspace = true }
trezoa-runtime = { workspace = true }
trezoa-sdk = { workspace = true }
trezoa-tpu-client = { workspace = true }

[dev-dependencies]
trezoa-logger = { workspace = true }
trezoa-runtime = { workspace = true, features = ["dev-context-only-utils"] }

[package.metadata.docs.rs]
targets = ["x86_64-unknown-linux-gnu"]
