[package]
name = "trezoa-send-transaction-service"
description = "Trezoa send transaction service"
documentation = "https://docs.rs/trezoa-send-transaction-service"
version = { workspace = true }
authors = { workspace = true }
repository = { workspace = true }
homepage = { workspace = true }
license = { workspace = true }
edition = { workspace = true }

[package.metadata.docs.rs]
targets = ["x86_64-unknown-linux-gnu"]

[features]
trezoa-unstable-api = []
dev-context-only-utils = ["trezoa-net-utils"]

[dependencies]
async-trait = { workspace = true }
crossbeam-channel = { workspace = true }
itertools = { workspace = true }
log = { workspace = true }
trezoa-client = { workspace = true }
trezoa-clock = { workspace = true }
trezoa-hash = { workspace = true }
trezoa-keypair = { workspace = true }
trezoa-measure = { workspace = true }
trezoa-metrics = { workspace = true }
trezoa-net-utils = { workspace = true, optional = true }
trezoa-nonce-account = { workspace = true }
trezoa-pubkey = { workspace = true }
trezoa-quic-definitions = { workspace = true }
trezoa-runtime = { workspace = true }
trezoa-signature = { workspace = true }
trezoa-time-utils = { workspace = true }
trezoa-tpu-client-next = { workspace = true, features = ["metrics"] }
tokio = { workspace = true, features = ["full"] }
tokio-util = { workspace = true }

[dev-dependencies]
trezoa-logger = { workspace = true }
trezoa-account = { workspace = true }
trezoa-fee-calculator = { workspace = true }
trezoa-genesis-config = { workspace = true }
trezoa-net-utils = { workspace = true }
trezoa-nonce = { workspace = true }
trezoa-runtime = { workspace = true, features = ["dev-context-only-utils"] }
trezoa-signer = { workspace = true }
trezoa-system-interface = { workspace = true }
trezoa-system-transaction = { workspace = true }
