[package]
name = "trezoa-sbf-rust-sanity"
documentation = "https://docs.rs/trezoa-sbf-rust-sanity"
version = { workspace = true }
description = { workspace = true }
authors = { workspace = true }
repository = { workspace = true }
homepage = { workspace = true }
license = { workspace = true }
edition = { workspace = true }

[features]
test-bpf = []
dummy-for-ci-check = ["test-bpf"]

[dependencies]
trezoa-program = { workspace = true }

[dev-dependencies]
trezoa-program-runtime = { workspace = true }
trezoa-program-test = { workspace = true }
trezoa-sdk = { workspace = true }

[lib]
crate-type = ["cdylib", "lib"]

[package.metadata.docs.rs]
targets = ["x86_64-unknown-linux-gnu"]
