[package]
name = "trezoa-poh"
description = "Trezoa PoH"
documentation = "https://docs.rs/trezoa-poh"
version = { workspace = true }
authors = { workspace = true }
repository = { workspace = true }
homepage = { workspace = true }
license = { workspace = true }
edition = { workspace = true }

[dependencies]
core_affinity = { workspace = true }
crossbeam-channel = { workspace = true }
log = { workspace = true }
trezoa-entry = { workspace = true }
trezoa-ledger = { workspace = true }
trezoa-measure = { workspace = true }
trezoa-metrics = { workspace = true }
trezoa-runtime = { workspace = true }
trezoa-sdk = { workspace = true }
thiserror = { workspace = true }

[dev-dependencies]
assert_matches = { workspace = true }
bincode = { workspace = true }
rand = { workspace = true }
trezoa-logger = { workspace = true }
trezoa-perf = { workspace = true }
trezoa-poh = { path = ".", features = ["dev-context-only-utils"] }
trezoa-runtime = { workspace = true, features = ["dev-context-only-utils"] }

[features]
dev-context-only-utils = []

[lib]
crate-type = ["lib"]
name = "trezoa_poh"

[[bench]]
name = "poh"

[package.metadata.docs.rs]
targets = ["x86_64-unknown-linux-gnu"]
