[package]
name = "trezoa-vote-program"
description = "Trezoa Vote program"
documentation = "https://docs.rs/trezoa-vote-program"
version = { workspace = true }
authors = { workspace = true }
repository = { workspace = true }
homepage = { workspace = true }
license = { workspace = true }
edition = { workspace = true }

[dependencies]
bincode = { workspace = true }
log = { workspace = true }
num-derive = { workspace = true }
num-traits = { workspace = true }
serde = { workspace = true }
serde_derive = { workspace = true }
trezoa-frozen-abi = { workspace = true }
trezoa-frozen-abi-macro = { workspace = true }
trezoa-metrics = { workspace = true }
trezoa-program = { workspace = true }
trezoa-program-runtime = { workspace = true }
trezoa-sdk = { workspace = true }
thiserror = { workspace = true }

[dev-dependencies]
assert_matches = { workspace = true }
trezoa-logger = { workspace = true }
test-case = { workspace = true }

[build-dependencies]
rustc_version = { workspace = true }

[lib]
crate-type = ["lib"]
name = "trezoa_vote_program"

[package.metadata.docs.rs]
targets = ["x86_64-unknown-linux-gnu"]
