[package]
name = "trezoa-metrics"
description = "Trezoa Metrics"
documentation = "https://docs.rs/trezoa-metrics"
version = { workspace = true }
authors = { workspace = true }
repository = { workspace = true }
homepage = { workspace = true }
license = { workspace = true }
edition = { workspace = true }

[package.metadata.docs.rs]
targets = ["x86_64-unknown-linux-gnu"]

[lib]
name = "trezoa_metrics"

[features]
trezoa-unstable-api = []

[dependencies]
crossbeam-channel = { workspace = true }
gethostname = { workspace = true }
log = { workspace = true }
reqwest = { workspace = true, features = ["blocking", "brotli", "deflate", "gzip", "rustls-tls", "json"] }
trezoa-cluster-type = { workspace = true }
trezoa-sha256-hasher = { workspace = true }
trezoa-time-utils = { workspace = true }
thiserror = { workspace = true }

[dev-dependencies]
bencher = { workspace = true }
env_logger = { workspace = true }
rand = { workspace = true }
serial_test = { workspace = true }
trezoa-metrics = { path = ".", features = ["trezoa-unstable-api"] }
trezoa-sha256-hasher = { workspace = true, features = ["sha2"] }

[[bench]]
name = "metrics"
harness = false
